VB_HIST.de.push({
  id: "apartamento-4b",
  titulo: "O vizinho do 4B",
  genero: "Mistério",
  nivel: "A1–A2",
  desc: "Você acabou de se mudar para Leipzig. Há três dias o vizinho do 4B, um velho relojoeiro, não aparece, e a porta dele está destrancada.",
  inicio: "c1",
  cenas: {
    c1: {
      cap: "Três dias",
      p: [
        ["Seit zwei Wochen wohnst du in Leipzig, im vierten Stock. Dein Nachbar in 4B ist Herr Albrecht, ein alter Uhrmacher. Jeden Morgen um acht grüßt er dich auf der Treppe. Aber seit drei Tagen hast du ihn nicht gesehen.",
         "Há duas semanas você mora em Leipzig, no quarto andar. Seu vizinho do 4B é o senhor Albrecht, um velho relojoeiro. Toda manhã às oito ele cumprimenta você na escada. Mas há três dias você não o vê.",
         [["Seit zwei Wochen", "Há duas semanas", "seit|zwei|Woche"],
          ["wohnst du in Leipzig,", "você mora em Leipzig,", "wohnen|du|in"],
          ["im vierten Stock.", "no quarto andar.", "in|der"],
          ["Dein Nachbar in 4B", "Seu vizinho do 4B", "dein|Nachbar|in"],
          ["ist Herr Albrecht,", "é o senhor Albrecht,", "sein|Herr"],
          ["ein alter Uhrmacher.", "um velho relojoeiro.", "ein|alt"],
          ["Jeden Morgen um acht", "Toda manhã às oito", "jeder|Morgen|um|acht"],
          ["grüßt er dich", "ele cumprimenta você", "grüßen|er|du"],
          ["auf der Treppe.", "na escada.", "auf|der|Treppe"],
          ["Aber seit drei Tagen", "Mas há três dias", "aber|seit|drei|Tag"],
          ["hast du ihn nicht gesehen.", "você não o vê.", "haben|du|er|nicht|sehen"]]],
        ["Heute ist Freitag. Hinter seiner Tür miaut seine Katze Minna, laut und lange. Du klopfst. Niemand antwortet. Dann drückst du leicht gegen die Tür, und sie geht auf. Sie war nicht abgeschlossen.",
         "Hoje é sexta-feira. Atrás da porta dele, a gata Minna mia, alto e sem parar. Você bate. Ninguém responde. Então você empurra a porta de leve, e ela se abre. Não estava trancada.",
         [["Heute ist Freitag.", "Hoje é sexta-feira.", "heute|sein|Freitag"],
          ["Hinter seiner Tür", "Atrás da porta dele,", "hinter|sein|Tür"],
          ["miaut seine Katze Minna,", "a gata dele, Minna, mia,", "sein|Katze"],
          ["laut und lange.", "alto e sem parar.", "laut|und|lang"],
          ["Du klopfst.", "Você bate.", "du|klopfen"],
          ["Niemand antwortet.", "Ninguém responde.", "niemand|antworten"],
          ["Dann drückst du", "Então você empurra", "dann|drücken|du"],
          ["leicht gegen die Tür,", "a porta de leve,", "leicht|gegen|der|Tür"],
          ["und sie geht auf.", "e ela se abre.", "und|sie|gehen"],
          ["Sie war nicht abgeschlossen.", "Não estava trancada.", "sie|sein|nicht"]]],
        ["In der Wohnung ist es still, nur die Uhren an den Wänden ticken. Minna läuft zu dir und miaut laut vor Hunger. Auf dem Tisch liegt ein Zettel: „H3 / 312 / Mi 7:00“. An der Wand ist ein Platz leer. Dort war immer die Uhr aus Gold.",
         "No apartamento está tudo quieto, só os relógios nas paredes fazem tique-taque. Minna corre até você e mia alto de fome. Na mesa há um bilhete: “H3 / 312 / Mi 7:00”. Na parede há um lugar vazio. Ali sempre ficava o relógio de ouro.",
         [["In der Wohnung", "No apartamento", "in|der|Wohnung"],
          ["ist es still,", "está tudo quieto,", "sein|es"],
          ["nur die Uhren", "só os relógios", "nur|der|Uhr"],
          ["an den Wänden", "nas paredes", "an|der|Wand"],
          ["ticken.", "fazem tique-taque.", ""],
          ["Minna läuft zu dir", "Minna corre até você", "laufen|zu|du"],
          ["und miaut laut vor Hunger.", "e mia alto de fome.", "und|laut|vor|Hunger"],
          ["Auf dem Tisch", "Na mesa", "auf|der|Tisch"],
          ["liegt ein Zettel:", "há um bilhete:", "liegen|ein"],
          ["„H3 / 312 / Mi 7:00“.", "“H3 / 312 / Mi 7:00”.", ""],
          ["An der Wand", "Na parede", "an|der|Wand"],
          ["ist ein Platz leer.", "há um lugar vazio.", "sein|ein|Platz|leer"],
          ["Dort war immer", "Ali sempre ficava", "dort|sein|immer"],
          ["die Uhr aus Gold.", "o relógio de ouro.", "der|Uhr|aus|Gold"]]]
      ],
      escolhas: [
        { pt: "Fotografar o bilhete com o celular.", de: "Den Zettel mit dem Handy fotografieren.", ir: "c2", marca: "foto" },
        { pt: "Dar comida à gata primeiro.", de: "Zuerst der Katze etwas zu essen geben.", ir: "c3", marca: "gata" },
        { pt: "Descer e chamar a Frau Krüger, a senhoria.", de: "Nach unten gehen und Frau Krüger holen.", ir: "c4" }
      ]
    },

    c2: {
      cap: "Jonas",
      p: [
        ["Du machst schnell ein Foto vom Zettel. Da hörst du Schritte auf der Treppe. Ein junger Mann steht in der Tür, mit einem Schlüssel in der Hand. Er ist sehr blass. „Wer bist du? Was machst du hier? Das ist die Wohnung meines Onkels!“",
         "Você tira rápido uma foto do bilhete. Nesse momento você ouve passos na escada. Um rapaz está parado na porta, com uma chave na mão. Ele está muito pálido. “Quem é você? O que você está fazendo aqui? Este é o apartamento do meu tio!”",
         [["Du machst schnell", "Você tira rápido", "du|machen|schnell"],
          ["ein Foto vom Zettel.", "uma foto do bilhete.", "ein|Foto|von|der"],
          ["Da hörst du", "Nesse momento você ouve", "da|hören|du"],
          ["Schritte auf der Treppe.", "passos na escada.", "auf|der|Treppe"],
          ["Ein junger Mann", "Um rapaz", "ein|jung|Mann"],
          ["steht in der Tür,", "está parado na porta,", "stehen|in|der|Tür"],
          ["mit einem Schlüssel", "com uma chave", "mit|ein|Schlüssel"],
          ["in der Hand.", "na mão.", "in|der|Hand"],
          ["Er ist sehr blass.", "Ele está muito pálido.", "er|sein|sehr"],
          ["„Wer bist du?", "“Quem é você?", "wer|sein|du"],
          ["Was machst du hier?", "O que você está fazendo aqui?", "was|machen|du|hier"],
          ["Das ist die Wohnung", "Este é o apartamento", "das|sein|der|Wohnung"],
          ["meines Onkels!“", "do meu tio!”", "mein|Onkel"]]],
        ["Er heißt Jonas. Er sagt, sein Onkel ist sicher bei einem Freund. Aber seine Augen gehen immer wieder zur leeren Stelle an der Wand. Die Katze miaut laut. Jonas sieht sie nicht an. Seine Hände zittern.",
         "Ele se chama Jonas. Ele diz que o tio com certeza está na casa de um amigo. Mas os olhos dele voltam o tempo todo para o lugar vazio na parede. A gata mia alto. Jonas nem olha para ela. As mãos dele tremem.",
         [["Er heißt Jonas.", "Ele se chama Jonas.", "er|heißen"],
          ["Er sagt,", "Ele diz", "er|sagen"],
          ["sein Onkel ist sicher", "que o tio com certeza está", "sein|Onkel|sicher"],
          ["bei einem Freund.", "na casa de um amigo.", "bei|ein|Freund"],
          ["Aber seine Augen", "Mas os olhos dele", "aber|sein|Auge"],
          ["gehen immer wieder", "voltam o tempo todo", "gehen|immer|wieder"],
          ["zur leeren Stelle", "para o lugar vazio", "zu|der|leer|Stelle"],
          ["an der Wand.", "na parede.", "an|der|Wand"],
          ["Die Katze miaut laut.", "A gata mia alto.", "der|Katze|laut"],
          ["Jonas sieht sie nicht an.", "Jonas nem olha para ela.", "sehen|sie|nicht"],
          ["Seine Hände zittern.", "As mãos dele tremem.", "sein|Hand"]]]
      ],
      escolhas: [
        { pt: "Perguntar sobre o relógio de ouro.", de: "Nach der Uhr aus Gold fragen.", ir: "c5" },
        { pt: "Sair e chamar a polícia.", de: "Gehen und die Polizei rufen.", ir: "c6" }
      ]
    },

    c3: {
      cap: "Minna",
      p: [
        ["Im Kühlschrank findest du etwas Wurst. Minna frisst alles in einer Minute. Dann läuft sie ins Schlafzimmer und setzt sich vor den Schrank. Sie sieht dich an, als ob sie etwas sagen wollte.",
         "Na geladeira você encontra um pouco de linguiça. Minna come tudo em um minuto. Depois ela corre para o quarto e se senta na frente do armário. Ela olha para você como se quisesse dizer alguma coisa.",
         [["Im Kühlschrank", "Na geladeira", "in|der|Kühlschrank"],
          ["findest du etwas Wurst.", "você encontra um pouco de linguiça.", "finden|du|etwas|Wurst"],
          ["Minna frisst alles", "Minna come tudo", "alles"],
          ["in einer Minute.", "em um minuto.", "in|ein|Minute"],
          ["Dann läuft sie", "Depois ela corre", "dann|laufen|sie"],
          ["ins Schlafzimmer", "para o quarto", "in|der"],
          ["und setzt sich", "e se senta", "und|setzen|sich"],
          ["vor den Schrank.", "na frente do armário.", "vor|der|Schrank"],
          ["Sie sieht dich an,", "Ela olha para você", "sie|sehen|du"],
          ["als ob sie etwas sagen wollte.", "como se quisesse dizer alguma coisa.", "als|ob|sie|etwas|sagen|wollen"]]],
        ["Du öffnest den Schrank. Die Hemden hängen ordentlich, aber der kleine Koffer fehlt. Im Bad findest du keine Zahnbürste und keine Medikamente. Herr Albrecht ist also nicht einfach verschwunden. Er hat seine Sachen gepackt.",
         "Você abre o armário. As camisas estão penduradas em ordem, mas a mala pequena não está lá. No banheiro você não encontra escova de dentes nem remédios. Então o senhor Albrecht não simplesmente sumiu. Ele arrumou as coisas dele.",
         [["Du öffnest den Schrank.", "Você abre o armário.", "du|öffnen|der|Schrank"],
          ["Die Hemden hängen ordentlich,", "As camisas estão penduradas em ordem,", "der|Hemd"],
          ["aber der kleine Koffer", "mas a mala pequena", "aber|der|klein|Koffer"],
          ["fehlt.", "não está lá.", "fehlen"],
          ["Im Bad", "No banheiro", "in|der|Bad"],
          ["findest du keine Zahnbürste", "você não encontra escova de dentes", "finden|du|kein"],
          ["und keine Medikamente.", "nem remédios.", "und|kein|Medikament"],
          ["Herr Albrecht ist also", "Então o senhor Albrecht", "Herr|sein|also"],
          ["nicht einfach verschwunden.", "não simplesmente sumiu.", "nicht|einfach"],
          ["Er hat seine Sachen gepackt.", "Ele arrumou as coisas dele.", "er|haben|sein|Sache"]]],
        ["Da öffnet sich die Wohnungstür. Ein junger Mann kommt herein, mit einem Schlüssel in der Hand. „Wer bist du?“, fragt er scharf. Er heißt Jonas und ist der Neffe von Herrn Albrecht. Er sieht die Katze, dann den leeren Teller und wird rot.",
         "Nesse momento se abre a porta do apartamento. Um rapaz entra, com uma chave na mão. “Quem é você?”, ele pergunta, ríspido. Ele se chama Jonas e é sobrinho do senhor Albrecht. Ele vê a gata, depois o prato vazio, e fica vermelho.",
         [["Da öffnet sich", "Nesse momento se abre", "da|öffnen|sich"],
          ["die Wohnungstür.", "a porta do apartamento.", "der"],
          ["Ein junger Mann kommt herein,", "Um rapaz entra,", "ein|jung|Mann|kommen"],
          ["mit einem Schlüssel", "com uma chave", "mit|ein|Schlüssel"],
          ["in der Hand.", "na mão.", "in|der|Hand"],
          ["„Wer bist du?“,", "“Quem é você?”,", "wer|sein|du"],
          ["fragt er scharf.", "ele pergunta, ríspido.", "fragen|er|scharf"],
          ["Er heißt Jonas", "Ele se chama Jonas", "er|heißen"],
          ["und ist der Neffe", "e é sobrinho", "und|sein|der"],
          ["von Herrn Albrecht.", "do senhor Albrecht.", "von|Herr"],
          ["Er sieht die Katze,", "Ele vê a gata,", "er|sehen|der|Katze"],
          ["dann den leeren Teller", "depois o prato vazio,", "dann|der|leer|Teller"],
          ["und wird rot.", "e fica vermelho.", "und|werden|rot"]]]
      ],
      escolhas: [
        { pt: "Mostrar a Jonas o armário sem a mala.", de: "Jonas den Schrank ohne Koffer zeigen.", ir: "c7" },
        { pt: "Perguntar sobre o relógio de ouro.", de: "Nach der Uhr aus Gold fragen.", ir: "c5" }
      ]
    },

    c4: {
      cap: "Frau Krüger",
      p: [
        ["Frau Krüger wohnt unten und vermietet das ganze Haus. Sie ist über siebzig, aber sie kommt schnell die Treppe hoch. In der Wohnung sagt sie sofort: „Nichts anfassen!“ Dann sieht sie den Zettel und den leeren Platz an der Wand.",
         "A Frau Krüger mora no térreo e aluga o prédio inteiro. Ela tem mais de setenta anos, mas sobe a escada rápido. No apartamento ela diz na hora: “Não toque em nada!” Depois ela vê o bilhete e o lugar vazio na parede.",
         [["Frau Krüger wohnt unten", "A Frau Krüger mora no térreo", "Frau|wohnen|unten"],
          ["und vermietet das ganze Haus.", "e aluga o prédio inteiro.", "und|der|ganz|Haus"],
          ["Sie ist über siebzig,", "Ela tem mais de setenta anos,", "sie|sein|über"],
          ["aber sie kommt schnell", "mas ela sobe rápido", "aber|sie|kommen|schnell"],
          ["die Treppe hoch.", "a escada.", "der|Treppe"],
          ["In der Wohnung", "No apartamento", "in|der|Wohnung"],
          ["sagt sie sofort:", "ela diz na hora:", "sagen|sie|sofort"],
          ["„Nichts anfassen!“", "“Não toque em nada!”", "nichts"],
          ["Dann sieht sie den Zettel", "Depois ela vê o bilhete", "dann|sehen|sie|der"],
          ["und den leeren Platz", "e o lugar vazio", "und|der|leer|Platz"],
          ["an der Wand.", "na parede.", "an|der|Wand"]]],
        ["„Die Uhr aus Gold! Die war von seinem Vater“, sagt sie leise. „Am Sonntag hat er laut mit Jonas gestritten, seinem Neffen. Es war wegen Geld. Der Junge hat Schulden, wissen Sie.“ Dann sieht sie dich ernst an.",
         "“O relógio de ouro! Era do pai dele”, ela diz baixinho. “No domingo ele brigou alto com o Jonas, o sobrinho dele. Foi por causa de dinheiro. O rapaz tem dívidas, sabe?” Depois ela olha para você com seriedade.",
         [["„Die Uhr aus Gold!", "“O relógio de ouro!", "der|Uhr|aus|Gold"],
          ["Die war von seinem Vater“,", "Era do pai dele”,", "die|sein|von|Vater"],
          ["sagt sie leise.", "ela diz baixinho.", "sagen|sie|leise"],
          ["„Am Sonntag", "“No domingo", "an|der|Sonntag"],
          ["hat er laut mit Jonas gestritten,", "ele brigou alto com o Jonas,", "haben|er|laut|mit|streiten"],
          ["seinem Neffen.", "o sobrinho dele.", "sein"],
          ["Es war wegen Geld.", "Foi por causa de dinheiro.", "es|sein|wegen|Geld"],
          ["Der Junge hat Schulden,", "O rapaz tem dívidas,", "der|Junge|haben"],
          ["wissen Sie.“", "sabe?”", "wissen|sie"],
          ["Dann sieht sie dich", "Depois ela olha para você", "dann|sehen|sie|du"],
          ["ernst an.", "com seriedade.", "ernst"]]]
      ],
      escolhas: [
        { pt: "Fotografar o bilhete e chamar a polícia.", de: "Den Zettel fotografieren und die Polizei rufen.", ir: "c6", marca: "foto" },
        { pt: "Ligar para o Jonas e pedir que ele venha.", de: "Jonas anrufen und ihn bitten zu kommen.", ir: "c7" }
      ]
    },

    c5: {
      cap: "O lugar vazio",
      p: [
        ["„Wo ist die Uhr aus Gold?“, fragst du. Jonas wird laut. „Willst du sagen, ich bin ein Dieb? Du kennst mich nicht! Du kennst meine Familie nicht!“ Er nimmt den Zettel vom Tisch, steckt ihn in die Tasche und läuft die Treppe hinunter.",
         "“Onde está o relógio de ouro?”, você pergunta. Jonas levanta a voz. “Você está dizendo que eu sou um ladrão? Você não me conhece! Você não conhece a minha família!” Ele pega o bilhete da mesa, põe no bolso e desce a escada correndo.",
         [["„Wo ist die Uhr", "“Onde está o relógio", "wo|sein|der|Uhr"],
          ["aus Gold?“,", "de ouro?”,", "aus|Gold"],
          ["fragst du.", "você pergunta.", "fragen|du"],
          ["Jonas wird laut.", "Jonas levanta a voz.", "werden|laut"],
          ["„Willst du sagen,", "“Você está dizendo", "wollen|du|sagen"],
          ["ich bin ein Dieb?", "que eu sou um ladrão?", "ich|sein|ein|Dieb"],
          ["Du kennst mich nicht!", "Você não me conhece!", "du|kennen|ich|nicht"],
          ["Du kennst meine Familie nicht!“", "Você não conhece a minha família!”", "du|kennen|mein|Familie|nicht"],
          ["Er nimmt den Zettel", "Ele pega o bilhete", "er|nehmen|der"],
          ["vom Tisch,", "da mesa,", "von|der|Tisch"],
          ["steckt ihn in die Tasche", "põe no bolso", "er|in|der|Tasche"],
          ["und läuft", "e corre", "und|laufen"],
          ["die Treppe hinunter.", "escada abaixo.", "der|Treppe"]]],
        ["Unten geht eine Tür auf. Frau Krüger, die Vermieterin, kommt die Treppe hoch und sieht dich lange an. „Was machen Sie in seiner Wohnung?“, fragt sie. „Und warum schreit der Junge so?“ Du merkst: Jetzt bist du hier die fremde Person.",
         "Lá embaixo uma porta se abre. A Frau Krüger, a senhoria, sobe a escada e olha para você por um bom tempo. “O que você está fazendo no apartamento dele?”, ela pergunta. “E por que o rapaz está gritando assim?” Você percebe: agora, aqui, a pessoa estranha é você.",
         [["Unten geht eine Tür auf.", "Lá embaixo uma porta se abre.", "unten|gehen|ein|Tür"],
          ["Frau Krüger, die Vermieterin,", "A Frau Krüger, a senhoria,", "Frau|der"],
          ["kommt die Treppe hoch", "sobe a escada", "kommen|der|Treppe"],
          ["und sieht dich lange an.", "e olha para você por um bom tempo.", "und|sehen|du|lang"],
          ["„Was machen Sie", "“O que você está fazendo", "was|machen|sie"],
          ["in seiner Wohnung?“,", "no apartamento dele?”,", "in|sein|Wohnung"],
          ["fragt sie.", "ela pergunta.", "fragen|sie"],
          ["„Und warum schreit der Junge so?“", "“E por que o rapaz está gritando assim?”", "und|warum|schreien|der|Junge|so"],
          ["Du merkst:", "Você percebe:", "du|merken"],
          ["Jetzt bist du hier", "Agora, aqui, você é", "jetzt|sein|du|hier"],
          ["die fremde Person.", "a pessoa estranha.", "der|fremd|Person"]]]
      ],
      escolhas: [
        { pt: "Chamar a polícia.", de: "Die Polizei rufen.", ir: "c6" },
        { pt: "Correr atrás do Jonas.", de: "Jonas hinterherlaufen.", ir: "c7" },
        { pt: "Mostrar à Frau Krüger a foto do bilhete.", de: "Frau Krüger das Foto vom Zettel zeigen.", ir: "c8", req: "foto" }
      ]
    },

    c6: {
      cap: "A polícia",
      p: [
        ["Eine halbe Stunde später steht eine Polizistin in der Wohnung. Sie heißt Frau Wendt und schreibt alles auf. Der Zettel ist nicht mehr auf dem Tisch. „Jonas war vorhin hier“, sagt Frau Krüger. „Er hat einen Schlüssel.“",
         "Meia hora depois há uma policial no apartamento. Ela se chama Frau Wendt e anota tudo. O bilhete não está mais na mesa. “O Jonas esteve aqui agora há pouco”, diz a Frau Krüger. “Ele tem uma chave.”",
         [["Eine halbe Stunde später", "Meia hora depois", "ein|Stunde|später"],
          ["steht eine Polizistin", "há uma policial", "stehen|ein"],
          ["in der Wohnung.", "no apartamento.", "in|der|Wohnung"],
          ["Sie heißt Frau Wendt", "Ela se chama Frau Wendt", "sie|heißen|Frau"],
          ["und schreibt alles auf.", "e anota tudo.", "und|schreiben|alles"],
          ["Der Zettel", "O bilhete", "der"],
          ["ist nicht mehr", "não está mais", "sein|nicht|mehr"],
          ["auf dem Tisch.", "na mesa.", "auf|der|Tisch"],
          ["„Jonas war vorhin hier“,", "“O Jonas esteve aqui agora há pouco”,", "sein|hier"],
          ["sagt Frau Krüger.", "diz a Frau Krüger.", "sagen|Frau"],
          ["„Er hat einen Schlüssel.“", "“Ele tem uma chave.”", "er|haben|ein|Schlüssel"]]],
        ["Frau Wendt bleibt ruhig. „Alte Menschen fahren oft ins Krankenhaus und sagen niemandem etwas“, erklärt sie. „Aber eine Uhr aus Gold, die fehlt, ist etwas anderes.“ Sie sieht dich an. „Und Sie waren vor uns in der Wohnung, richtig?“",
         "Frau Wendt continua calma. “Pessoas idosas muitas vezes vão para o hospital e não dizem nada a ninguém”, ela explica. “Mas um relógio de ouro que sumiu é outra coisa.” Ela olha para você. “E você estava no apartamento antes de nós, certo?”",
         [["Frau Wendt bleibt ruhig.", "Frau Wendt continua calma.", "Frau|bleiben|ruhig"],
          ["„Alte Menschen", "“Pessoas idosas", "alt|Mensch"],
          ["fahren oft ins Krankenhaus", "muitas vezes vão para o hospital", "fahren|oft|in|der|Krankenhaus"],
          ["und sagen niemandem etwas“,", "e não dizem nada a ninguém”,", "und|sagen|niemand|etwas"],
          ["erklärt sie.", "ela explica.", "erklären|sie"],
          ["„Aber eine Uhr aus Gold,", "“Mas um relógio de ouro", "aber|ein|Uhr|aus|Gold"],
          ["die fehlt,", "que sumiu", "die|fehlen"],
          ["ist etwas anderes.“", "é outra coisa.”", "sein|etwas|ander"],
          ["Sie sieht dich an.", "Ela olha para você.", "sie|sehen|du"],
          ["„Und Sie waren", "“E você estava", "und|sie|sein"],
          ["vor uns in der Wohnung,", "no apartamento antes de nós,", "vor|wir|in|der|Wohnung"],
          ["richtig?“", "certo?”", "richtig"]]]
      ],
      escolhas: [
        { pt: "Dizer que o Jonas roubou o relógio.", de: "Sagen, dass Jonas die Uhr gestohlen hat.", ir: "f_ruim" },
        { pt: "Responder às perguntas e deixar a polícia trabalhar.", de: "Die Fragen beantworten und die Polizei arbeiten lassen.", ir: "f_neutro" },
        { pt: "Mostrar a foto do bilhete.", de: "Das Foto vom Zettel zeigen.", ir: "c8", req: "foto" }
      ]
    },

    c7: {
      cap: "Jonas fala",
      p: [
        ["Jonas setzt sich auf die Treppe und legt die Hände vors Gesicht. „Mein Onkel hat Probleme mit dem Herzen“, sagt er leise. „Am Dienstag hat er mich angerufen. Er wollte, dass ich Minna Essen gebe. Nur ein paar Tage, hat er gesagt.“",
         "Jonas se senta na escada e põe as mãos no rosto. “Meu tio tem problemas de coração”, ele diz baixinho. “Na terça ele me ligou. Ele queria que eu desse comida para a Minna. Só uns dias, ele disse.”",
         [["Jonas setzt sich", "Jonas se senta", "setzen|sich"],
          ["auf die Treppe", "na escada", "auf|der|Treppe"],
          ["und legt die Hände", "e põe as mãos", "und|legen|der|Hand"],
          ["vors Gesicht.", "no rosto.", "vor|der|Gesicht"],
          ["„Mein Onkel", "“Meu tio", "mein|Onkel"],
          ["hat Probleme mit dem Herzen“,", "tem problemas de coração”,", "haben|Problem|mit|der|Herz"],
          ["sagt er leise.", "ele diz baixinho.", "sagen|er|leise"],
          ["„Am Dienstag", "“Na terça", "an|der|Dienstag"],
          ["hat er mich angerufen.", "ele me ligou.", "haben|er|ich|anrufen"],
          ["Er wollte,", "Ele queria", "er|wollen"],
          ["dass ich Minna Essen gebe.", "que eu desse comida para a Minna.", "dass|ich|Essen|geben"],
          ["Nur ein paar Tage,", "Só uns dias,", "nur|ein|Tag"],
          ["hat er gesagt.“", "ele disse.”", "haben|er|sagen"]]],
        ["„Ich bin nicht gekommen. Wir hatten Streit, und ich habe mich geschämt.“ Er sieht zur Seite. Er weiß nicht, in welchem Krankenhaus sein Onkel liegt. Und über die Uhr aus Gold sagt er kein Wort.",
         "“Eu não vim. A gente tinha brigado, e eu fiquei com vergonha.” Ele desvia o olhar. Ele não sabe em que hospital o tio está. E sobre o relógio de ouro ele não diz uma palavra.",
         [["„Ich bin nicht gekommen.", "“Eu não vim.", "ich|sein|nicht|kommen"],
          ["Wir hatten Streit,", "A gente tinha brigado,", "wir|haben|Streit"],
          ["und ich habe mich geschämt.“", "e eu fiquei com vergonha.”", "und|ich|haben"],
          ["Er sieht zur Seite.", "Ele desvia o olhar.", "er|sehen|zu|der|Seite"],
          ["Er weiß nicht,", "Ele não sabe", "er|wissen|nicht"],
          ["in welchem Krankenhaus sein Onkel liegt.", "em que hospital o tio está.", "in|welcher|Krankenhaus|sein|Onkel|liegen"],
          ["Und über die Uhr", "E sobre o relógio", "und|über|der|Uhr"],
          ["aus Gold", "de ouro", "aus|Gold"],
          ["sagt er kein Wort.", "ele não diz uma palavra.", "sagen|er|kein|Wort"]]]
      ],
      escolhas: [
        { pt: "Procurar o hospital junto com o Jonas.", de: "Mit Jonas das Krankenhaus suchen.", ir: "c8" },
        { pt: "Deixar a família resolver isso.", de: "Das der Familie überlassen.", ir: "f_neutro" }
      ]
    },

    c8: {
      cap: "Quarto 312",
      nota: "Os números do bilhete finalmente fazem sentido.",
      p: [
        ["Die Zahlen waren kein Code. H3 ist Haus 3 im großen Krankenhaus im Süden der Stadt. 312 ist ein Zimmer. Und am Mittwoch um sieben Uhr war die Operation. Herr Albrecht liegt im Bett, blass und dünn, aber er lebt.",
         "Os números não eram um código. H3 é o prédio 3 do grande hospital no sul da cidade. 312 é um quarto. E na quarta-feira às sete horas foi a cirurgia. O senhor Albrecht está deitado na cama, pálido e magro, mas está vivo.",
         [["Die Zahlen", "Os números", "der|Zahl"],
          ["waren kein Code.", "não eram um código.", "sein|kein"],
          ["H3 ist Haus 3", "H3 é o prédio 3", "sein|Haus"],
          ["im großen Krankenhaus", "do grande hospital", "in|der|groß|Krankenhaus"],
          ["im Süden der Stadt.", "no sul da cidade.", "in|der|Stadt"],
          ["312 ist ein Zimmer.", "312 é um quarto.", "sein|ein|Zimmer"],
          ["Und am Mittwoch", "E na quarta-feira", "und|an|der|Mittwoch"],
          ["um sieben Uhr", "às sete horas", "um|sieben|Uhr"],
          ["war die Operation.", "foi a cirurgia.", "sein|der"],
          ["Herr Albrecht liegt im Bett,", "O senhor Albrecht está deitado na cama,", "Herr|liegen|in|der|Bett"],
          ["blass und dünn,", "pálido e magro,", "und|dünn"],
          ["aber er lebt.", "mas está vivo.", "aber|er|leben"]]],
        ["„Ich wollte niemandem etwas sagen“, erklärt er. „Ein alter Mann mit einem schwachen Herzen, wer will das hören?“ Er lacht leise. Dann fragt er: „Und Minna? Jonas sollte ihr Essen geben. Hat er das gemacht?“",
         "“Eu não queria dizer nada a ninguém”, ele explica. “Um homem velho com o coração fraco, quem quer ouvir isso?” Ele ri baixinho. Depois ele pergunta: “E a Minna? O Jonas devia dar comida para ela. Ele fez isso?”",
         [["„Ich wollte niemandem etwas sagen“,", "“Eu não queria dizer nada a ninguém”,", "ich|wollen|niemand|etwas|sagen"],
          ["erklärt er.", "ele explica.", "erklären|er"],
          ["„Ein alter Mann", "“Um homem velho", "ein|alt|Mann"],
          ["mit einem schwachen Herzen,", "com o coração fraco,", "mit|ein|schwach|Herz"],
          ["wer will das hören?“", "quem quer ouvir isso?”", "wer|wollen|das|hören"],
          ["Er lacht leise.", "Ele ri baixinho.", "er|lachen|leise"],
          ["Dann fragt er:", "Depois ele pergunta:", "dann|fragen|er"],
          ["„Und Minna?", "“E a Minna?", "und"],
          ["Jonas sollte ihr Essen geben.", "O Jonas devia dar comida para ela.", "sollen|sie|Essen|geben"],
          ["Hat er das gemacht?“", "Ele fez isso?”", "haben|er|das|machen"]]]
      ],
      escolhas: [
        { pt: "Contar que o relógio de ouro sumiu.", de: "Erzählen, dass die Uhr aus Gold fehlt.", ir: "f_ruim" },
        { pt: "Não dizer nada sobre o relógio.", de: "Nichts über die Uhr sagen.", ir: "f_segredo" },
        { pt: "Contar que você deu comida para a Minna.", de: "Erzählen, dass du Minna Essen gegeben hast.", ir: "f_bom", req: "gata" }
      ]
    },

    f_bom: {
      cap: "A chave",
      p: [
        ["Du erzählst von Minna, von der Wurst aus dem Kühlschrank und vom fehlenden Koffer. Herr Albrecht hört zu und nimmt deine Hand. „Danke“, sagt er. Dann wird er ernst. „Die Uhr aus Gold ist weg, nicht wahr? Ich weiß, wer sie hat.“",
         "Você fala da Minna, da linguiça da geladeira e da mala que faltava. O senhor Albrecht escuta e pega sua mão. “Obrigado”, ele diz. Depois ele fica sério. “O relógio de ouro sumiu, não é? Eu sei quem está com ele.”",
         [["Du erzählst von Minna,", "Você fala da Minna,", "du|erzählen|von"],
          ["von der Wurst", "da linguiça", "von|der|Wurst"],
          ["aus dem Kühlschrank", "da geladeira", "aus|der|Kühlschrank"],
          ["und vom fehlenden Koffer.", "e da mala que faltava.", "und|von|der|fehlen|Koffer"],
          ["Herr Albrecht hört zu", "O senhor Albrecht escuta", "Herr|hören"],
          ["und nimmt deine Hand.", "e pega sua mão.", "und|nehmen|dein|Hand"],
          ["„Danke“, sagt er.", "“Obrigado”, ele diz.", "danke|sagen|er"],
          ["Dann wird er ernst.", "Depois ele fica sério.", "dann|werden|er|ernst"],
          ["„Die Uhr aus Gold", "“O relógio de ouro", "der|Uhr|aus|Gold"],
          ["ist weg, nicht wahr?", "sumiu, não é?", "sein|weg|nicht"],
          ["Ich weiß,", "Eu sei", "ich|wissen"],
          ["wer sie hat.“", "quem está com ele.”", "wer|sie|haben"]]],
        ["Am nächsten Tag kommt Jonas ins Krankenhaus, mit der Uhr in der Hand. Er hat sie zurückgekauft, mit dem Geld für seinen Urlaub. Lange sagen die beiden nichts. Dann legt Herr Albrecht dir einen Schlüssel in die Hand: „Für Minna. Bis ich zurück bin.“",
         "No dia seguinte, Jonas chega ao hospital com o relógio na mão. Ele o comprou de volta com o dinheiro das férias dele. Por muito tempo os dois não dizem nada. Então o senhor Albrecht coloca uma chave na sua mão: “Para a Minna. Até eu voltar.”",
         [["Am nächsten Tag", "No dia seguinte", "an|der|nächste|Tag"],
          ["kommt Jonas", "Jonas chega", "kommen"],
          ["ins Krankenhaus,", "ao hospital,", "in|der|Krankenhaus"],
          ["mit der Uhr", "com o relógio", "mit|der|Uhr"],
          ["in der Hand.", "na mão.", "in|der|Hand"],
          ["Er hat sie zurückgekauft,", "Ele o comprou de volta,", "er|haben|sie|kaufen"],
          ["mit dem Geld", "com o dinheiro", "mit|der|Geld"],
          ["für seinen Urlaub.", "das férias dele.", "für|sein|Urlaub"],
          ["Lange sagen die beiden nichts.", "Por muito tempo os dois não dizem nada.", "lang|sagen|der|nichts"],
          ["Dann legt Herr Albrecht", "Então o senhor Albrecht coloca", "dann|legen|Herr"],
          ["dir einen Schlüssel in die Hand:", "uma chave na sua mão:", "du|ein|Schlüssel|in|der|Hand"],
          ["„Für Minna.", "“Para a Minna.", "für"],
          ["Bis ich zurück bin.“", "Até eu voltar.”", "bis|ich|zurück|sein"]]]
      ],
      fim: { tipo: "bom", titulo: "A chave do 4B" }
    },

    f_neutro: {
      cap: "Assunto de família",
      p: [
        ["Am Montag erzählt dir Frau Krüger die Neuigkeit: Herr Albrecht liegt im Krankenhaus. Er hatte eine Operation am Herzen, und es geht ihm besser. Minna wohnt jetzt bei ihr unten, bis er zurückkommt.",
         "Na segunda-feira, a Frau Krüger conta a novidade para você: o senhor Albrecht está internado no hospital. Ele fez uma cirurgia no coração e está melhor. A Minna agora mora com ela lá embaixo, até ele voltar.",
         [["Am Montag", "Na segunda-feira", "an|der|Montag"],
          ["erzählt dir Frau Krüger", "a Frau Krüger conta para você", "erzählen|du|Frau"],
          ["die Neuigkeit:", "a novidade:", "der"],
          ["Herr Albrecht liegt", "O senhor Albrecht está internado", "Herr|liegen"],
          ["im Krankenhaus.", "no hospital.", "in|der|Krankenhaus"],
          ["Er hatte eine Operation", "Ele fez uma cirurgia", "er|haben|ein"],
          ["am Herzen,", "no coração,", "an|der|Herz"],
          ["und es geht ihm besser.", "e está melhor.", "und|es|gehen|er|besser"],
          ["Minna wohnt jetzt", "A Minna agora mora", "wohnen|jetzt"],
          ["bei ihr unten,", "com ela lá embaixo,", "bei|sie|unten"],
          ["bis er zurückkommt.", "até ele voltar.", "bis|er"]]],
        ["Was mit der Uhr passiert ist, erfährst du nie. Jonas sieht dich auf der Straße und geht schnell auf die andere Seite. Es ist nicht dein Problem, denkst du. Aber manchmal, wenn nebenan die Uhren ticken, fragst du dich doch.",
         "O que aconteceu com o relógio você nunca vai saber. Jonas vê você na rua e atravessa rápido para o outro lado. Não é problema seu, você pensa. Mas às vezes, quando os relógios fazem tique-taque ao lado, você fica se perguntando.",
         [["Was mit der Uhr passiert ist,", "O que aconteceu com o relógio", "was|mit|der|Uhr|passieren|sein"],
          ["erfährst du nie.", "você nunca vai saber.", "du|nie"],
          ["Jonas sieht dich", "Jonas vê você", "sehen|du"],
          ["auf der Straße", "na rua", "auf|der|Straße"],
          ["und geht schnell", "e atravessa rápido", "und|gehen|schnell"],
          ["auf die andere Seite.", "para o outro lado.", "auf|der|ander|Seite"],
          ["Es ist nicht dein Problem,", "Não é problema seu,", "es|sein|nicht|dein|Problem"],
          ["denkst du.", "você pensa.", "denken|du"],
          ["Aber manchmal,", "Mas às vezes,", "aber|manchmal"],
          ["wenn nebenan die Uhren ticken,", "quando os relógios fazem tique-taque ao lado,", "wenn|der|Uhr"],
          ["fragst du dich doch.", "você fica se perguntando.", "fragen|du|doch"]]]
      ],
      fim: { tipo: "neutro", titulo: "Assunto de família" }
    },

    f_segredo: {
      cap: "O relógio volta",
      p: [
        ["Du sagst nichts über die Uhr. Herr Albrecht kommt nach zehn Tagen nach Hause, langsam, mit einem Stock. Am Abend hängt die Uhr aus Gold wieder an der Wand. Niemand erklärt, wie sie dorthin gekommen ist.",
         "Você não diz nada sobre o relógio. O senhor Albrecht volta para casa depois de dez dias, devagar, de bengala. À noite o relógio de ouro está pendurado de novo na parede. Ninguém explica como ele voltou para lá.",
         [["Du sagst nichts", "Você não diz nada", "du|sagen|nichts"],
          ["über die Uhr.", "sobre o relógio.", "über|der|Uhr"],
          ["Herr Albrecht kommt", "O senhor Albrecht volta", "Herr|kommen"],
          ["nach zehn Tagen", "depois de dez dias", "nach|zehn|Tag"],
          ["nach Hause,", "para casa,", "nach|Haus"],
          ["langsam, mit einem Stock.", "devagar, de bengala.", "langsam|mit|ein"],
          ["Am Abend", "À noite", "an|der|Abend"],
          ["hängt die Uhr aus Gold", "o relógio de ouro está pendurado", "der|Uhr|aus|Gold"],
          ["wieder an der Wand.", "de novo na parede.", "wieder|an|der|Wand"],
          ["Niemand erklärt,", "Ninguém explica", "niemand|erklären"],
          ["wie sie dorthin gekommen ist.", "como ele voltou para lá.", "wie|sie|kommen|sein"]]],
        ["Auf der Treppe nickt Jonas dir kurz zu. Er weiß, dass du es weißt. Aber du weißt nicht, ob er seine Schulden bezahlt hat oder neue hat. Ihr teilt jetzt ein Geheimnis, und du wolltest es nie.",
         "Na escada, Jonas faz um aceno rápido para você. Ele sabe que você sabe. Mas você não sabe se ele pagou as dívidas ou se tem dívidas novas. Agora vocês dividem um segredo, e você nunca quis isso.",
         [["Auf der Treppe", "Na escada,", "auf|der|Treppe"],
          ["nickt Jonas dir kurz zu.", "Jonas faz um aceno rápido para você.", "du|kurz"],
          ["Er weiß,", "Ele sabe", "er|wissen"],
          ["dass du es weißt.", "que você sabe.", "dass|du|es|wissen"],
          ["Aber du weißt nicht,", "Mas você não sabe", "aber|du|wissen|nicht"],
          ["ob er seine Schulden bezahlt hat", "se ele pagou as dívidas", "ob|er|sein|bezahlen|haben"],
          ["oder neue hat.", "ou se tem dívidas novas.", "oder|neu|haben"],
          ["Ihr teilt jetzt", "Agora vocês dividem", "ihr|teilen|jetzt"],
          ["ein Geheimnis,", "um segredo,", "ein|Geheimnis"],
          ["und du wolltest es nie.", "e você nunca quis isso.", "und|du|wollen|es|nie"]]]
      ],
      fim: { tipo: "neutro", titulo: "Um segredo dividido" }
    },

    f_ruim: {
      cap: "Perguntas na porta",
      p: [
        ["Zwei Tage später klingelt es an deiner Tür. Es ist Frau Wendt von der Polizei. Herr Albrecht will seine Uhr zurück. Jonas sagt, er war seit Sonntag nicht dort. Und Frau Krüger erzählt allen, wer zuerst in der Wohnung war: du.",
         "Dois dias depois, tocam a campainha da sua porta. É a Frau Wendt, da polícia. O senhor Albrecht quer o relógio dele de volta. Jonas diz que não vai lá desde domingo. E a Frau Krüger conta para todo mundo quem entrou primeiro no apartamento: você.",
         [["Zwei Tage später", "Dois dias depois,", "zwei|Tag|später"],
          ["klingelt es an deiner Tür.", "tocam a campainha da sua porta.", "klingeln|es|an|dein|Tür"],
          ["Es ist Frau Wendt", "É a Frau Wendt,", "es|sein|Frau"],
          ["von der Polizei.", "da polícia.", "von|der|Polizei"],
          ["Herr Albrecht will", "O senhor Albrecht quer", "Herr|wollen"],
          ["seine Uhr zurück.", "o relógio dele de volta.", "sein|Uhr|zurück"],
          ["Jonas sagt,", "Jonas diz", "sagen"],
          ["er war seit Sonntag nicht dort.", "que não vai lá desde domingo.", "er|sein|seit|Sonntag|nicht|dort"],
          ["Und Frau Krüger", "E a Frau Krüger", "und|Frau"],
          ["erzählt allen,", "conta para todo mundo", "erzählen|alle"],
          ["wer zuerst in der Wohnung war:", "quem entrou primeiro no apartamento:", "wer|zuerst|in|der|Wohnung|sein"],
          ["du.", "você.", "du"]]],
        ["Du erklärst alles noch einmal: die Katze, die offene Tür, den Zettel. Frau Wendt schreibt und nickt, aber sie lächelt nicht. Herr Albrecht kommt bald nach Hause. Aber wenn du klopfst, öffnet er nicht mehr.",
         "Você explica tudo mais uma vez: a gata, a porta aberta, o bilhete. Frau Wendt anota e acena com a cabeça, mas não sorri. O senhor Albrecht logo volta para casa. Mas quando você bate, ele não abre mais.",
         [["Du erklärst alles", "Você explica tudo", "du|erklären|alles"],
          ["noch einmal:", "mais uma vez:", "noch"],
          ["die Katze,", "a gata,", "der|Katze"],
          ["die offene Tür,", "a porta aberta,", "der|offen|Tür"],
          ["den Zettel.", "o bilhete.", "der"],
          ["Frau Wendt schreibt", "Frau Wendt anota", "Frau|schreiben"],
          ["und nickt,", "e acena com a cabeça,", "und"],
          ["aber sie lächelt nicht.", "mas não sorri.", "aber|sie|nicht"],
          ["Herr Albrecht kommt", "O senhor Albrecht volta", "Herr|kommen"],
          ["bald nach Hause.", "logo para casa.", "bald|nach|Haus"],
          ["Aber wenn du klopfst,", "Mas quando você bate,", "aber|wenn|du|klopfen"],
          ["öffnet er nicht mehr.", "ele não abre mais.", "öffnen|er|nicht|mehr"]]]
      ],
      fim: { tipo: "ruim", titulo: "Do lado errado da porta" }
    }
  }
});
