VB_HIST.de.push({
  id: "quarto-livre",
  titulo: "Quarto livre",
  genero: "Cotidiano",
  nivel: "A1–A2",
  desc: "Você tem uma semana para achar um quarto em Munique e se registrar na prefeitura. Sem endereço, não há conta no banco, e sem conta não há salário.",
  inicio: "c1",
  cenas: {
    c1: {
      cap: "Uma semana",
      p: [
        ["Es ist Montag, sieben Uhr. Du bist in einem Hostel in München, in einem Zimmer mit elf anderen Leuten. Am nächsten Montag hast du einen Termin beim Bürgeramt. Ohne Anmeldung bekommst du kein Konto, und ohne Konto bekommst du kein Gehalt.",
         "É segunda-feira, sete horas. Você está num hostel em Munique, num quarto com outras onze pessoas. Na próxima segunda você tem horário marcado no Bürgeramt, a repartição de registro. Sem o registro de residência você não consegue conta no banco, e sem conta você não recebe salário.",
         [["Es ist Montag,", "É segunda-feira,", "es|sein|Montag"],
          ["sieben Uhr.", "sete horas.", "sieben|Uhr"],
          ["Du bist", "Você está", "du|sein"],
          ["in einem Hostel", "num hostel", "in|ein"],
          ["in München,", "em Munique,", "in"],
          ["in einem Zimmer", "num quarto", "in|ein|Zimmer"],
          ["mit elf anderen Leuten.", "com outras onze pessoas.", "mit|elf|ander|Leute"],
          ["Am nächsten Montag", "Na próxima segunda", "an|der|nächste|Montag"],
          ["hast du einen Termin", "você tem horário marcado", "haben|du|ein|Termin"],
          ["beim Bürgeramt.", "no Bürgeramt, a repartição de registro.", "bei|der"],
          ["Ohne Anmeldung", "Sem o registro de residência", "ohne"],
          ["bekommst du kein Konto,", "você não consegue conta no banco,", "bekommen|du|kein|Konto"],
          ["und ohne Konto", "e sem conta", "und|ohne|Konto"],
          ["bekommst du kein Gehalt.", "você não recebe salário.", "bekommen|du|kein|Gehalt"]]],
        ["Der Mann im Bürgeramt hat es am Telefon klar gesagt: Du brauchst eine Bestätigung vom Vermieter. Auf deinem Handy gibt es zwei Möglichkeiten. Eine WG in Schwabing sucht jemanden, Casting heute um 19 Uhr, „bitte pünktlich!!!“ Und eine Anzeige: ein großes Zimmer im Zentrum, nur 400 Euro, sofort frei.",
         "O homem do Bürgeramt foi bem claro ao telefone: você precisa de uma confirmação do proprietário. No seu celular há duas possibilidades. Um apartamento compartilhado em Schwabing procura alguém, casting hoje às 19h, “por favor, pontualidade!!!” E um anúncio: um quarto grande no centro, só 400 euros, livre já.",
         [["Der Mann im Bürgeramt", "O homem do Bürgeramt", "der|Mann|in|der"],
          ["hat es am Telefon", "falou ao telefone", "haben|es|an|der|Telefon"],
          ["klar gesagt:", "com toda a clareza:", "klar|sagen"],
          ["Du brauchst eine Bestätigung", "você precisa de uma confirmação", "du|brauchen|ein"],
          ["vom Vermieter.", "do proprietário.", "von|der"],
          ["Auf deinem Handy", "No seu celular", "auf|dein|Handy"],
          ["gibt es zwei Möglichkeiten.", "há duas possibilidades.", "geben|es|zwei|Möglichkeit"],
          ["Eine WG in Schwabing", "Um apartamento compartilhado em Schwabing", "ein|in"],
          ["sucht jemanden,", "procura alguém,", "suchen|jemand"],
          ["Casting heute um 19 Uhr,", "casting hoje às 19h,", "heute|um|Uhr"],
          ["„bitte pünktlich!!!“", "“por favor, pontualidade!!!”", "bitte|pünktlich"],
          ["Und eine Anzeige:", "E um anúncio:", "und|ein"],
          ["ein großes Zimmer im Zentrum,", "um quarto grande no centro,", "ein|groß|Zimmer|in|der|Zentrum"],
          ["nur 400 Euro,", "só 400 euros,", "nur|Euro"],
          ["sofort frei.", "livre já.", "sofort|frei"]]],
        ["Unter der Anzeige der WG steht noch ein Satz: „Die Vermieterin, Frau Huber, wohnt unten und entscheidet mit.“ Neben dem Hostel ist eine Bäckerei. Im Fenster steht ein Apfelkuchen.",
         "Embaixo do anúncio do apartamento ainda há uma frase: “A senhoria, a senhora Huber, mora no térreo e também decide.” Ao lado do hostel há uma padaria. Na vitrine está um bolo de maçã.",
         [["Unter der Anzeige der WG", "Embaixo do anúncio do apartamento", "unter|der"],
          ["steht noch ein Satz:", "ainda há uma frase:", "stehen|noch|ein|Satz"],
          ["„Die Vermieterin, Frau Huber,", "“A senhoria, a senhora Huber,", "der|Frau"],
          ["wohnt unten", "mora no térreo", "wohnen|unten"],
          ["und entscheidet mit.“", "e também decide.”", "und|entscheiden"],
          ["Neben dem Hostel", "Ao lado do hostel", "neben|der"],
          ["ist eine Bäckerei.", "há uma padaria.", "sein|ein"],
          ["Im Fenster", "Na vitrine", "in|der|Fenster"],
          ["steht ein Apfelkuchen.", "está um bolo de maçã.", "stehen|ein|Apfel|Kuchen"]]]
      ],
      escolhas: [
        { pt: "Comprar o bolo de maçã para a senhora Huber e ir ao casting.", de: "Den Apfelkuchen für Frau Huber kaufen und zum Casting gehen.", ir: "c2", marca: "bolo" },
        { pt: "Responder primeiro ao anúncio barato.", de: "Zuerst auf die billige Anzeige antworten.", ir: "c3" }
      ]
    },

    c2: {
      cap: "O casting",
      p: [
        ["Um 19 Uhr stehst du vor einem alten Haus in Schwabing. Unten sitzt eine alte Frau am Fenster und beobachtet dich. Oben öffnet Lena die Tür. Sie hat ein Tablet in der Hand. Am Kühlschrank hängt ein Putzplan in fünf Farben.",
         "Às 19h você está diante de um prédio antigo em Schwabing. Embaixo, uma senhora idosa está sentada à janela e observa você. Lá em cima, Lena abre a porta. Ela tem um tablet na mão. Na geladeira está pendurado um plano de limpeza em cinco cores.",
         [["Um 19 Uhr", "Às 19h", "um|Uhr"],
          ["stehst du", "você está", "stehen|du"],
          ["vor einem alten Haus", "diante de um prédio antigo", "vor|ein|alt|Haus"],
          ["in Schwabing.", "em Schwabing.", "in"],
          ["Unten sitzt eine alte Frau", "Embaixo, uma senhora idosa está sentada", "unten|sitzen|ein|alt|Frau"],
          ["am Fenster", "à janela", "an|der|Fenster"],
          ["und beobachtet dich.", "e observa você.", "und|beobachten|du"],
          ["Oben öffnet Lena die Tür.", "Lá em cima, Lena abre a porta.", "oben|öffnen|der|Tür"],
          ["Sie hat ein Tablet", "Ela tem um tablet", "sie|haben|ein"],
          ["in der Hand.", "na mão.", "in|der|Hand"],
          ["Am Kühlschrank hängt", "Na geladeira está pendurado", "an|der|Kühlschrank"],
          ["ein Putzplan in fünf Farben.", "um plano de limpeza em cinco cores.", "ein|in|fünf|Farbe"]]],
        ["In der Küche sitzt Tobias ohne Schuhe und spielt leise Gitarre. Lena stellt Fragen wie bei einer Prüfung: Job, Kochen, Wochenende. Dann schaut sie dich an. „Letzte Frage. Rauchst du?“ Tobias hört auf zu spielen. Deine Jacke riecht noch nach der Zigarette von heute Mittag.",
         "Na cozinha está Tobias, descalço, tocando violão baixinho. Lena faz perguntas como numa prova: trabalho, cozinha, fim de semana. Então ela olha para você. “Última pergunta. Você fuma?” Tobias para de tocar. Sua jaqueta ainda cheira ao cigarro de hoje ao meio-dia.",
         [["In der Küche", "Na cozinha", "in|der|Küche"],
          ["sitzt Tobias", "está Tobias,", "sitzen"],
          ["ohne Schuhe", "descalço,", "ohne|Schuh"],
          ["und spielt leise Gitarre.", "tocando violão baixinho.", "und|spielen|leise"],
          ["Lena stellt Fragen", "Lena faz perguntas", "stellen|Frage"],
          ["wie bei einer Prüfung:", "como numa prova:", "wie|bei|ein|Prüfung"],
          ["Job, Kochen, Wochenende.", "trabalho, cozinha, fim de semana.", "Job|kochen|Wochenende"],
          ["Dann schaut sie dich an.", "Então ela olha para você.", "dann|schauen|sie|du"],
          ["„Letzte Frage.", "“Última pergunta.", "letzte|Frage"],
          ["Rauchst du?“", "Você fuma?”", "rauchen|du"],
          ["Tobias hört auf zu spielen.", "Tobias para de tocar.", "aufhören|zu|spielen"],
          ["Deine Jacke riecht noch", "Sua jaqueta ainda cheira", "dein|Jacke|riechen|noch"],
          ["nach der Zigarette", "ao cigarro", "nach|der"],
          ["von heute Mittag.", "de hoje ao meio-dia.", "von|heute|Mittag"]]]
      ],
      escolhas: [
        { pt: "Mentir: “Não, nunca.”", de: "Lügen: „Nein, nie.“", ir: "c4", marca: "mentiu" },
        { pt: "Dizer a verdade: às vezes, mas só lá fora.", de: "Die Wahrheit sagen: manchmal, aber nur draußen.", ir: "c5" }
      ]
    },

    c3: {
      cap: "Boa demais",
      p: [
        ["Nach fünf Minuten antwortet ein Mann namens Max. Er schreibt halb Englisch, halb Deutsch. Er ist gerade in London, leider. Die Fotos sind sehr schön, fast wie in einem Hotel. „Ein Besuch ist nicht möglich, aber ich schicke dir den Schlüssel mit der Post.“",
         "Depois de cinco minutos responde um homem chamado Max. Ele escreve meio em inglês, meio em alemão. Ele está em Londres agora, infelizmente. As fotos são muito bonitas, quase como num hotel. “Uma visita não é possível, mas eu te mando a chave pelo correio.”",
         [["Nach fünf Minuten", "Depois de cinco minutos", "nach|fünf|Minute"],
          ["antwortet ein Mann namens Max.", "responde um homem chamado Max.", "antworten|ein|Mann"],
          ["Er schreibt", "Ele escreve", "er|schreiben"],
          ["halb Englisch, halb Deutsch.", "meio em inglês, meio em alemão.", "deutsch"],
          ["Er ist gerade in London,", "Ele está em Londres agora,", "er|sein|gerade|in"],
          ["leider.", "infelizmente.", "leider"],
          ["Die Fotos sind sehr schön,", "As fotos são muito bonitas,", "der|Foto|sein|sehr|schön"],
          ["fast wie in einem Hotel.", "quase como num hotel.", "fast|wie|in|ein|Hotel"],
          ["„Ein Besuch", "“Uma visita", "ein"],
          ["ist nicht möglich,", "não é possível,", "sein|nicht|möglich"],
          ["aber ich schicke dir", "mas eu te mando", "aber|ich|schicken|du"],
          ["den Schlüssel", "a chave", "der|Schlüssel"],
          ["mit der Post.“", "pelo correio.”", "mit|der|Post"]]],
        ["Dann kommt die zweite Nachricht: „Bitte zuerst die Kaution überweisen, 1200 Euro. Dann bekommst du den Schlüssel und die Bestätigung für das Amt.“ Du rechnest. Das ist mehr als die Hälfte von deinem Geld. Aber es ist ein großes Zimmer im Zentrum, für 400 Euro.",
         "Então chega a segunda mensagem: “Por favor, primeiro transfira a caução, 1200 euros. Depois você recebe a chave e a confirmação para o órgão público.” Você faz as contas. Isso é mais da metade do seu dinheiro. Mas é um quarto grande no centro, por 400 euros.",
         [["Dann kommt", "Então chega", "dann|kommen"],
          ["die zweite Nachricht:", "a segunda mensagem:", "der|Nachricht"],
          ["„Bitte zuerst", "“Por favor, primeiro", "bitte|zuerst"],
          ["die Kaution überweisen,", "transfira a caução,", "der"],
          ["1200 Euro.", "1200 euros.", "Euro"],
          ["Dann bekommst du", "Depois você recebe", "dann|bekommen|du"],
          ["den Schlüssel", "a chave", "der|Schlüssel"],
          ["und die Bestätigung", "e a confirmação", "und|der"],
          ["für das Amt.“", "para o órgão público.”", "für|der"],
          ["Du rechnest.", "Você faz as contas.", "du|rechnen"],
          ["Das ist mehr", "Isso é mais", "der|sein|mehr"],
          ["als die Hälfte", "da metade", "als|der|Hälfte"],
          ["von deinem Geld.", "do seu dinheiro.", "von|dein|Geld"],
          ["Aber es ist", "Mas é", "aber|es|sein"],
          ["ein großes Zimmer im Zentrum,", "um quarto grande no centro,", "ein|groß|Zimmer|in|der|Zentrum"],
          ["für 400 Euro.", "por 400 euros.", "für|Euro"]]]
      ],
      escolhas: [
        { pt: "Transferir a caução. Uma chance dessas não volta.", de: "Die Kaution überweisen. So eine Chance kommt nicht wieder.", ir: "c6" },
        { pt: "Não pagar nada e ir ao Bürgeramt perguntar o que fazer.", de: "Nichts zahlen und im Bürgeramt fragen.", ir: "c8" }
      ]
    },

    c4: {
      cap: "A resposta perfeita",
      p: [
        ["Lena lächelt zum ersten Mal. „Perfekt. Hier raucht niemand.“ Tobias hustet und schaut aus dem Fenster. Dann erklärt Lena die Regeln: Ruhe ab 22 Uhr, Glas nur werktags, Papier in die blaue Tonne. Die Miete ist 640 Euro, bar, jeden Monat in einem Umschlag.",
         "Lena sorri pela primeira vez. “Perfeito. Aqui ninguém fuma.” Tobias tosse e olha pela janela. Então Lena explica as regras: silêncio a partir das 22h, vidro só em dia útil, papel na lixeira azul. O aluguel é 640 euros, em dinheiro, todo mês num envelope.",
         [["Lena lächelt zum ersten Mal.", "Lena sorri pela primeira vez.", "zu|der|erste"],
          ["„Perfekt.", "“Perfeito.", ""],
          ["Hier raucht niemand.“", "Aqui ninguém fuma.”", "hier|rauchen|niemand"],
          ["Tobias hustet", "Tobias tosse", ""],
          ["und schaut aus dem Fenster.", "e olha pela janela.", "und|schauen|aus|der|Fenster"],
          ["Dann erklärt Lena die Regeln:", "Então Lena explica as regras:", "dann|erklären|der"],
          ["Ruhe ab 22 Uhr,", "silêncio a partir das 22h,", "Ruhe|Uhr"],
          ["Glas nur werktags,", "vidro só em dia útil,", "Glas|nur"],
          ["Papier in die blaue Tonne.", "papel na lixeira azul.", "Papier|in|der|blau"],
          ["Die Miete ist 640 Euro,", "O aluguel é 640 euros,", "der|Miete|sein|Euro"],
          ["bar,", "em dinheiro,", ""],
          ["jeden Monat", "todo mês", "jeder|Monat"],
          ["in einem Umschlag.", "num envelope.", "in|ein"]]],
        ["„Das Zimmer ist ab Samstag frei“, sagt Lena. „Aber Frau Huber unten entscheidet. Nur sie unterschreibt die Bestätigung.“ An der Tür flüstert Tobias: „Netter Versuch. Ich rauche auch, auf dem Balkon, wenn Lena schläft.“",
         "“O quarto fica livre a partir de sábado”, diz Lena. “Mas quem decide é a senhora Huber, lá de baixo. Só ela assina a confirmação.” Na porta, Tobias sussurra: “Boa tentativa. Eu também fumo, na varanda, quando a Lena dorme.”",
         [["„Das Zimmer ist", "“O quarto fica", "der|Zimmer|sein"],
          ["ab Samstag frei“,", "livre a partir de sábado”,", "Samstag|frei"],
          ["sagt Lena.", "diz Lena.", "sagen"],
          ["„Aber Frau Huber unten", "“Mas a senhora Huber, lá de baixo,", "aber|Frau|unten"],
          ["entscheidet.", "é quem decide.", "entscheiden"],
          ["Nur sie unterschreibt", "Só ela assina", "nur|sie"],
          ["die Bestätigung.“", "a confirmação.”", "der"],
          ["An der Tür", "Na porta,", "an|der|Tür"],
          ["flüstert Tobias:", "Tobias sussurra:", ""],
          ["„Netter Versuch.", "“Boa tentativa.", "nett"],
          ["Ich rauche auch,", "Eu também fumo,", "ich|rauchen|auch"],
          ["auf dem Balkon,", "na varanda,", "auf|der"],
          ["wenn Lena schläft.“", "quando a Lena dorme.”", "wenn|schlafen"]]]
      ],
      escolhas: [
        { pt: "Voltar amanhã cedo e falar com a senhora Huber.", de: "Morgen früh zu Frau Huber gehen.", ir: "c7" },
        { pt: "Ir ao Bürgeramt e tentar resolver sem ela.", de: "Zum Bürgeramt gehen und es ohne sie versuchen.", ir: "c8" }
      ]
    },

    c5: {
      cap: "A verdade",
      p: [
        ["Lena schreibt etwas auf ihr Tablet. Ihr Gesicht wird ernst. „Der Balkon ist für meine Pflanzen“, sagt sie. Tobias lacht laut. „Endlich mal jemand Ehrliches! Die letzten drei haben alle gelogen.“ Lena sagt nur: „Wir entscheiden am Mittwoch.“",
         "Lena escreve algo no tablet. O rosto dela fica sério. “A varanda é para as minhas plantas”, diz ela. Tobias ri alto. “Finalmente alguém sincero! Os últimos três mentiram, todos eles.” Lena só diz: “A gente decide na quarta.”",
         [["Lena schreibt etwas", "Lena escreve algo", "schreiben|etwas"],
          ["auf ihr Tablet.", "no tablet.", "auf|ihr"],
          ["Ihr Gesicht wird ernst.", "O rosto dela fica sério.", "ihr|Gesicht|werden|ernst"],
          ["„Der Balkon ist", "“A varanda é", "der|sein"],
          ["für meine Pflanzen“,", "para as minhas plantas”,", "für|mein|Pflanze"],
          ["sagt sie.", "diz ela.", "sagen|sie"],
          ["Tobias lacht laut.", "Tobias ri alto.", "lachen|laut"],
          ["„Endlich mal jemand Ehrliches!", "“Finalmente alguém sincero!", "endlich|mal|jemand"],
          ["Die letzten drei", "Os últimos três", "der|letzte|drei"],
          ["haben alle gelogen.“", "mentiram, todos eles.”", "haben|alle|lügen"],
          ["Lena sagt nur:", "Lena só diz:", "sagen|nur"],
          ["„Wir entscheiden am Mittwoch.“", "“A gente decide na quarta.”", "wir|entscheiden|an|der|Mittwoch"]]],
        ["An der Tür flüstert Tobias: „Lena hat hier nichts zu sagen. Die Wohnung gehört Frau Huber, unten. Sie mag keine Listen, und sie mag keine Lügen. Geh morgen zu ihr. Und nimm viel Zeit mit.“",
         "Na porta, Tobias sussurra: “Aqui a Lena não manda nada. O apartamento é da senhora Huber, lá de baixo. Ela não gosta de listas e não gosta de mentiras. Vá falar com ela amanhã. E leve bastante tempo.”",
         [["An der Tür", "Na porta,", "an|der|Tür"],
          ["flüstert Tobias:", "Tobias sussurra:", ""],
          ["„Lena hat hier", "“Aqui a Lena", "haben|hier"],
          ["nichts zu sagen.", "não manda nada.", "nichts|zu|sagen"],
          ["Die Wohnung gehört", "O apartamento é", "der|Wohnung|gehören"],
          ["Frau Huber, unten.", "da senhora Huber, lá de baixo.", "Frau|unten"],
          ["Sie mag keine Listen,", "Ela não gosta de listas,", "sie|mögen|kein"],
          ["und sie mag keine Lügen.", "e não gosta de mentiras.", "und|sie|mögen|kein|Lüge"],
          ["Geh morgen zu ihr.", "Vá falar com ela amanhã.", "gehen|morgen|zu|sie"],
          ["Und nimm viel Zeit mit.“", "E leve bastante tempo.”", "und|mitnehmen|viel|Zeit"]]]
      ],
      escolhas: [
        { pt: "Seguir o conselho e visitar a senhora Huber amanhã.", de: "Morgen Frau Huber besuchen.", ir: "c7" },
        { pt: "Não esperar ninguém e ir direto ao Bürgeramt.", de: "Auf niemanden warten und zum Bürgeramt gehen.", ir: "c8" }
      ]
    },

    c6: {
      cap: "A transferência",
      p: [
        ["Du überweist das Geld am Montagabend. Am Dienstag schreibt Max nicht. Am Mittwoch auch nicht. Am Donnerstag ist sein Profil weg, und die Nummer funktioniert nicht mehr. Deine Bank in Brasilien sagt am Telefon: „Das Geld ist schon in Litauen. Das tut mir leid.“",
         "Você transfere o dinheiro na segunda à noite. Na terça, Max não escreve. Na quarta também não. Na quinta, o perfil dele sumiu, e o número não funciona mais. Seu banco no Brasil diz ao telefone: “O dinheiro já está na Lituânia. Sinto muito.”",
         [["Du überweist das Geld", "Você transfere o dinheiro", "du|der|Geld"],
          ["am Montagabend.", "na segunda à noite.", "an|der"],
          ["Am Dienstag", "Na terça,", "an|der|Dienstag"],
          ["schreibt Max nicht.", "Max não escreve.", "schreiben|nicht"],
          ["Am Mittwoch auch nicht.", "Na quarta também não.", "an|der|Mittwoch|auch|nicht"],
          ["Am Donnerstag", "Na quinta,", "an|der|Donnerstag"],
          ["ist sein Profil weg,", "o perfil dele sumiu,", "sein|weg"],
          ["und die Nummer", "e o número", "und|der|Nummer"],
          ["funktioniert nicht mehr.", "não funciona mais.", "funktionieren|nicht|mehr"],
          ["Deine Bank in Brasilien", "Seu banco no Brasil", "dein|Bank|in"],
          ["sagt am Telefon:", "diz ao telefone:", "sagen|an|der|Telefon"],
          ["„Das Geld ist schon", "“O dinheiro já está", "der|Geld|sein|schon"],
          ["in Litauen.", "na Lituânia.", "in"],
          ["Das tut mir leid.“", "Sinto muito.”", "der|tun|ich"]]],
        ["Du hast noch 600 Euro und vier Tage bis zum Termin. Jonas vom Hostel sagt: „Für einen Monat bekommst du von mir eine Bestätigung. Aber das kostet 550 Euro, und das Zimmer teilst du mit fünf Leuten.“",
         "Você ainda tem 600 euros e quatro dias até o horário marcado. Jonas, do hostel, diz: “Por um mês você recebe de mim uma confirmação. Mas custa 550 euros, e você divide o quarto com cinco pessoas.”",
         [["Du hast noch 600 Euro", "Você ainda tem 600 euros", "du|haben|noch|Euro"],
          ["und vier Tage", "e quatro dias", "und|vier|Tag"],
          ["bis zum Termin.", "até o horário marcado.", "bis|zu|der|Termin"],
          ["Jonas vom Hostel sagt:", "Jonas, do hostel, diz:", "von|der|sagen"],
          ["„Für einen Monat", "“Por um mês", "für|ein|Monat"],
          ["bekommst du von mir", "você recebe de mim", "bekommen|du|von|ich"],
          ["eine Bestätigung.", "uma confirmação.", "ein"],
          ["Aber das kostet 550 Euro,", "Mas custa 550 euros,", "aber|der|kosten|Euro"],
          ["und das Zimmer", "e o quarto", "und|der|Zimmer"],
          ["teilst du", "você divide", "teilen|du"],
          ["mit fünf Leuten.“", "com cinco pessoas.”", "mit|fünf|Leute"]]]
      ],
      escolhas: [
        { pt: "Ir à polícia e lutar pelo dinheiro.", de: "Zur Polizei gehen und um das Geld kämpfen.", ir: "f_prazo" },
        { pt: "Pagar o hostel e garantir a confirmação.", de: "Das Hostel bezahlen und die Bestätigung nehmen.", ir: "f_prov" }
      ]
    },

    c7: {
      cap: "A senhora Huber",
      p: [
        ["Dienstag, neun Uhr. Frau Huber steht im Hof vor den Containern und hält eine grüne Flasche in die Luft. „Grünglas, Braunglas, Weißglas! Niemand in diesem Haus kann das.“ Sie schaut dich an. „Sie waren gestern oben. Und dann haben Sie geraucht, direkt vor meinem Fenster.“",
         "Terça, nove horas. A senhora Huber está no pátio, diante das lixeiras, e segura uma garrafa verde no alto. “Vidro verde, vidro marrom, vidro branco! Ninguém neste prédio sabe fazer isso.” Ela olha para você. “Você esteve lá em cima ontem. E depois você fumou, bem na frente da minha janela.”",
         [["Dienstag, neun Uhr.", "Terça, nove horas.", "Dienstag|neun|Uhr"],
          ["Frau Huber steht im Hof", "A senhora Huber está no pátio,", "Frau|stehen|in|der"],
          ["vor den Containern", "diante das lixeiras,", "vor|der"],
          ["und hält eine grüne Flasche", "e segura uma garrafa verde", "und|halten|ein|grün|Flasche"],
          ["in die Luft.", "no alto.", "in|der|Luft"],
          ["„Grünglas, Braunglas, Weißglas!", "“Vidro verde, vidro marrom, vidro branco!", "grün|braun|weiß|Glas"],
          ["Niemand in diesem Haus", "Ninguém neste prédio", "niemand|in|dieser|Haus"],
          ["kann das.“", "sabe fazer isso.”", "können|der"],
          ["Sie schaut dich an.", "Ela olha para você.", "sie|schauen|du"],
          ["„Sie waren gestern oben.", "“Você esteve lá em cima ontem.", "sie|sein|gestern|oben"],
          ["Und dann haben Sie geraucht,", "E depois você fumou,", "und|dann|haben|sie|rauchen"],
          ["direkt vor meinem Fenster.“", "bem na frente da minha janela.”", "vor|mein|Fenster"]]],
        ["Sie wirft die Flasche in den richtigen Container. „Ich will drei Dinge: die Miete bar, Ruhe nach zehn und keine Geschichten. Lena macht Listen, Tobias macht Musik. Und Sie? Was machen Sie?“ Der Termin ist in sechs Tagen. Sie hat noch nichts unterschrieben.",
         "Ela joga a garrafa no contêiner certo. “Eu quero três coisas: o aluguel em dinheiro, silêncio depois das dez e nada de histórias. A Lena faz listas, o Tobias faz música. E você? O que você faz?” O horário marcado é daqui a seis dias. Ela ainda não assinou nada.",
         [["Sie wirft die Flasche", "Ela joga a garrafa", "sie|werfen|der|Flasche"],
          ["in den richtigen Container.", "no contêiner certo.", "in|der|richtig"],
          ["„Ich will drei Dinge:", "“Eu quero três coisas:", "ich|wollen|drei|Ding"],
          ["die Miete bar,", "o aluguel em dinheiro,", "der|Miete"],
          ["Ruhe nach zehn", "silêncio depois das dez", "Ruhe|nach|zehn"],
          ["und keine Geschichten.", "e nada de histórias.", "und|kein|Geschichte"],
          ["Lena macht Listen,", "A Lena faz listas,", "machen"],
          ["Tobias macht Musik.", "o Tobias faz música.", "machen|Musik"],
          ["Und Sie?", "E você?", "und|sie"],
          ["Was machen Sie?“", "O que você faz?”", "was|machen|sie"],
          ["Der Termin ist", "O horário marcado é", "der|Termin|sein"],
          ["in sechs Tagen.", "daqui a seis dias.", "in|sechs|Tag"],
          ["Sie hat noch nichts unterschrieben.", "Ela ainda não assinou nada.", "sie|haben|noch|nichts"]]]
      ],
      escolhas: [
        { pt: "Entregar a ela o bolo de maçã que você comprou ontem.", de: "Ihr den Apfelkuchen von gestern geben.", ir: "f_bom", req: "bolo" },
        { pt: "Pegar as garrafas e ajudar a separar o vidro.", de: "Die Flaschen nehmen und beim Sortieren helfen.", ir: "c9" },
        { pt: "Desistir da senhora Huber e tentar no Bürgeramt.", de: "Frau Huber vergessen und es beim Bürgeramt versuchen.", ir: "c8" }
      ]
    },

    c8: {
      cap: "O Bürgeramt",
      p: [
        ["Mittwoch im Bürgeramt. Du ziehst eine Nummer und wartest zwei Stunden. Herr Becker hat eine Tasse Kaffee und keine Zeit. „Ohne Bestätigung vom Vermieter keine Anmeldung“, sagt er. „Ohne Anmeldung kein Konto“, sagst du. Er nickt. „Ja. So ist das.“",
         "Quarta-feira, no Bürgeramt. Você tira uma senha e espera duas horas. O senhor Becker tem uma xícara de café e nenhum tempo. “Sem confirmação do proprietário, nada de registro”, diz ele. “Sem registro, nada de conta”, diz você. Ele faz que sim. “Pois é. É assim.”",
         [["Mittwoch im Bürgeramt.", "Quarta-feira, no Bürgeramt.", "Mittwoch|in|der"],
          ["Du ziehst eine Nummer", "Você tira uma senha", "du|ziehen|ein|Nummer"],
          ["und wartest zwei Stunden.", "e espera duas horas.", "und|warten|zwei|Stunde"],
          ["Herr Becker hat", "O senhor Becker tem", "Herr|haben"],
          ["eine Tasse Kaffee", "uma xícara de café", "ein|Tasse|Kaffee"],
          ["und keine Zeit.", "e nenhum tempo.", "und|kein|Zeit"],
          ["„Ohne Bestätigung vom Vermieter", "“Sem confirmação do proprietário,", "ohne|von|der"],
          ["keine Anmeldung“,", "nada de registro”,", "kein"],
          ["sagt er.", "diz ele.", "sagen|er"],
          ["„Ohne Anmeldung kein Konto“,", "“Sem registro, nada de conta”,", "ohne|kein|Konto"],
          ["sagst du.", "diz você.", "sagen|du"],
          ["Er nickt.", "Ele faz que sim.", "er"],
          ["„Ja. So ist das.“", "“Pois é. É assim.”", "ja|so|sein|der"]]],
        ["Dann sieht er auf seinen Bildschirm. „Es gibt eine Möglichkeit. Auch ein Hostel kann bestätigen, wenn Sie dort wohnen. Oder Sie finden bis Freitag ein Zimmer.“ Er schaut auf die Uhr. Hinter dir warten noch vierzig Leute.",
         "Então ele olha para a tela. “Existe uma possibilidade. Um hostel também pode confirmar, se você morar lá. Ou você encontra um quarto até sexta.” Ele olha o relógio. Atrás de você esperam mais quarenta pessoas.",
         [["Dann sieht er", "Então ele olha", "dann|sehen|er"],
          ["auf seinen Bildschirm.", "para a tela.", "auf|sein|Bildschirm"],
          ["„Es gibt eine Möglichkeit.", "“Existe uma possibilidade.", "es|geben|ein|Möglichkeit"],
          ["Auch ein Hostel", "Um hostel também", "auch|ein"],
          ["kann bestätigen,", "pode confirmar,", "können"],
          ["wenn Sie dort wohnen.", "se você morar lá.", "wenn|sie|dort|wohnen"],
          ["Oder Sie finden", "Ou você encontra", "oder|sie|finden"],
          ["bis Freitag ein Zimmer.“", "um quarto até sexta.”", "bis|Freitag|ein|Zimmer"],
          ["Er schaut auf die Uhr.", "Ele olha o relógio.", "er|schauen|auf|der|Uhr"],
          ["Hinter dir warten", "Atrás de você esperam", "hinter|du|warten"],
          ["noch vierzig Leute.", "mais quarenta pessoas.", "noch|Leute"]]]
      ],
      escolhas: [
        { pt: "Aceitar o hostel por um mês. Melhor que nada.", de: "Einen Monat im Hostel nehmen. Besser als nichts.", ir: "f_prov" },
        { pt: "Insistir e pedir uma exceção ao senhor Becker.", de: "Herrn Becker um eine Ausnahme bitten.", ir: "f_prazo" }
      ]
    },

    c9: {
      cap: "Café de sábado",
      nota: "O que você respondeu no casting volta agora.",
      p: [
        ["Am Dienstag hast du eine Stunde lang Glas sortiert. Frau Huber hat gesagt: „Samstag, drei Uhr, Kaffee bei mir. Alle drei.“ Jetzt sitzt du an ihrem Tisch, zwischen Lena und Tobias. Es gibt Kuchen, aber niemand isst.",
         "Na terça, você passou uma hora separando vidro. A senhora Huber disse: “Sábado, três horas, café na minha casa. Os três.” Agora você está à mesa dela, entre Lena e Tobias. Tem bolo, mas ninguém come.",
         [["Am Dienstag", "Na terça,", "an|der|Dienstag"],
          ["hast du eine Stunde lang", "você passou uma hora", "haben|du|ein|Stunde|lang"],
          ["Glas sortiert.", "separando vidro.", "Glas"],
          ["Frau Huber hat gesagt:", "A senhora Huber disse:", "Frau|haben|sagen"],
          ["„Samstag, drei Uhr,", "“Sábado, três horas,", "Samstag|drei|Uhr"],
          ["Kaffee bei mir.", "café na minha casa.", "Kaffee|bei|ich"],
          ["Alle drei.“", "Os três.”", "alle|drei"],
          ["Jetzt sitzt du", "Agora você está", "jetzt|sitzen|du"],
          ["an ihrem Tisch,", "à mesa dela,", "an|ihr|Tisch"],
          ["zwischen Lena und Tobias.", "entre Lena e Tobias.", "zwischen|und"],
          ["Es gibt Kuchen,", "Tem bolo,", "es|geben|Kuchen"],
          ["aber niemand isst.", "mas ninguém come.", "aber|niemand|essen"]]],
        ["Lena legt eine Packung Zigaretten auf den Tisch. „Die hat im Flur gelegen, am Montag, nach dem Casting.“ Tobias schaut auf seinen Teller. Frau Huber trinkt langsam ihren Kaffee und wartet. „Ist das deine?“, fragt Lena.",
         "Lena coloca um maço de cigarros sobre a mesa. “Estava no corredor, na segunda, depois do casting.” Tobias olha para o prato. A senhora Huber toma devagar o café dela e espera. “É seu?”, pergunta Lena.",
         [["Lena legt", "Lena coloca", "legen"],
          ["eine Packung Zigaretten", "um maço de cigarros", "ein"],
          ["auf den Tisch.", "sobre a mesa.", "auf|der|Tisch"],
          ["„Die hat im Flur gelegen,", "“Estava no corredor,", "der|haben|in|der|liegen"],
          ["am Montag,", "na segunda,", "an|der|Montag"],
          ["nach dem Casting.“", "depois do casting.”", "nach|der"],
          ["Tobias schaut", "Tobias olha", "schauen"],
          ["auf seinen Teller.", "para o prato.", "auf|sein|Teller"],
          ["Frau Huber trinkt langsam", "A senhora Huber toma devagar", "Frau|trinken|langsam"],
          ["ihren Kaffee", "o café dela", "ihr|Kaffee"],
          ["und wartet.", "e espera.", "und|warten"],
          ["„Ist das deine?“,", "“É seu?”,", "sein|der|dein"],
          ["fragt Lena.", "pergunta Lena.", "fragen"]]]
      ],
      escolhas: [
        { pt: "Dizer que o maço é do Tobias.", de: "Sagen, dass die Packung Tobias gehört.", ir: "f_mentira", req: "mentiu" },
        { pt: "Confessar que mentiu no casting e pedir uma chance.", de: "Zugeben, dass du beim Casting gelogen hast.", ir: "f_prov", req: "mentiu" },
        { pt: "“É meu. Eu disse que fumo às vezes, lá fora.”", de: "„Ja, meine. Ich habe gesagt, dass ich manchmal draußen rauche.“", ir: "f_bom", sem: "mentiu" }
      ]
    },

    f_bom: {
      cap: "A assinatura",
      p: [
        ["Frau Huber nimmt einen Stift und unterschreibt. „Die Miete bar, am ersten Tag im Monat“, sagt sie. Lena gibt dir einen Schlüssel und eine Kopie vom Putzplan. Tobias zeigt dir den Balkon: „Hier ist die Welt noch in Ordnung.“",
         "A senhora Huber pega uma caneta e assina. “O aluguel em dinheiro, no primeiro dia do mês”, diz ela. Lena te dá uma chave e uma cópia do plano de limpeza. Tobias te mostra a varanda: “Aqui o mundo ainda está em ordem.”",
         [["Frau Huber nimmt einen Stift", "A senhora Huber pega uma caneta", "Frau|nehmen|ein"],
          ["und unterschreibt.", "e assina.", "und"],
          ["„Die Miete bar,", "“O aluguel em dinheiro,", "der|Miete"],
          ["am ersten Tag im Monat“,", "no primeiro dia do mês”,", "an|der|erste|Tag|in|der|Monat"],
          ["sagt sie.", "diz ela.", "sagen|sie"],
          ["Lena gibt dir", "Lena te dá", "geben|du"],
          ["einen Schlüssel", "uma chave", "ein|Schlüssel"],
          ["und eine Kopie vom Putzplan.", "e uma cópia do plano de limpeza.", "und|ein|von|der"],
          ["Tobias zeigt dir den Balkon:", "Tobias te mostra a varanda:", "zeigen|du|der"],
          ["„Hier ist die Welt", "“Aqui o mundo", "hier|sein|der|Welt"],
          ["noch in Ordnung.“", "ainda está em ordem.”", "noch|in|Ordnung"]]],
        ["Am Montag um acht Uhr legst du die Bestätigung auf den Tisch. Der Mann im Bürgeramt stempelt, ohne zu lächeln. Du hast eine Adresse in München. Auf dem Weg nach Hause lernst du die wichtigste Regel: Glas nie am Sonntag.",
         "Na segunda, às oito horas, você coloca a confirmação sobre a mesa. O homem do Bürgeramt carimba, sem sorrir. Você tem um endereço em Munique. No caminho para casa você aprende a regra mais importante: vidro nunca no domingo.",
         [["Am Montag um acht Uhr", "Na segunda, às oito horas,", "an|der|Montag|um|acht|Uhr"],
          ["legst du die Bestätigung", "você coloca a confirmação", "legen|du|der"],
          ["auf den Tisch.", "sobre a mesa.", "auf|der|Tisch"],
          ["Der Mann im Bürgeramt", "O homem do Bürgeramt", "der|Mann|in|der"],
          ["stempelt,", "carimba,", ""],
          ["ohne zu lächeln.", "sem sorrir.", "ohne|zu"],
          ["Du hast eine Adresse", "Você tem um endereço", "du|haben|ein|Adresse"],
          ["in München.", "em Munique.", "in"],
          ["Auf dem Weg nach Hause", "No caminho para casa", "auf|der|Weg|nach|Haus"],
          ["lernst du", "você aprende", "lernen|du"],
          ["die wichtigste Regel:", "a regra mais importante:", "der|wichtig"],
          ["Glas nie am Sonntag.", "vidro nunca no domingo.", "Glas|nie|an|der|Sonntag"]]]
      ],
      fim: { tipo: "bom", titulo: "Endereço em Munique" }
    },

    f_prov: {
      cap: "Solução provisória",
      p: [
        ["Es ist nicht die Lösung, die du wolltest: nur ein Monat, ein kleines Bett, viele Fragen. Aber am Montag um acht Uhr bekommst du deine Anmeldung. Jetzt kannst du ein Konto eröffnen und dein erstes Gehalt bekommen.",
         "Não é a solução que você queria: só um mês, uma cama pequena, muitas perguntas. Mas na segunda, às oito horas, você consegue seu registro. Agora você pode abrir uma conta e receber seu primeiro salário.",
         [["Es ist nicht die Lösung,", "Não é a solução", "es|sein|nicht|der"],
          ["die du wolltest:", "que você queria:", "der|du|wollen"],
          ["nur ein Monat,", "só um mês,", "nur|ein|Monat"],
          ["ein kleines Bett,", "uma cama pequena,", "ein|klein|Bett"],
          ["viele Fragen.", "muitas perguntas.", "viele|Frage"],
          ["Aber am Montag", "Mas na segunda,", "aber|an|der|Montag"],
          ["um acht Uhr", "às oito horas,", "um|acht|Uhr"],
          ["bekommst du deine Anmeldung.", "você consegue seu registro.", "bekommen|du|dein"],
          ["Jetzt kannst du", "Agora você pode", "jetzt|können|du"],
          ["ein Konto eröffnen", "abrir uma conta", "ein|Konto"],
          ["und dein erstes Gehalt bekommen.", "e receber seu primeiro salário.", "und|dein|erste|Gehalt|bekommen"]]],
        ["Am Abend schreibst du eine neue Nachricht an zwanzig WGs: „Ich koche gern, ich bin ruhig, und ich bringe Kuchen mit.“ In vier Wochen beginnt die Suche wieder. Aber diesmal hast du Zeit.",
         "À noite você escreve uma nova mensagem para vinte apartamentos compartilhados: “Eu gosto de cozinhar, sou uma pessoa tranquila e levo bolo.” Daqui a quatro semanas a busca começa de novo. Mas desta vez você tem tempo.",
         [["Am Abend schreibst du", "À noite você escreve", "an|der|Abend|schreiben|du"],
          ["eine neue Nachricht", "uma nova mensagem", "ein|neu|Nachricht"],
          ["an zwanzig WGs:", "para vinte apartamentos compartilhados:", "an|zwanzig"],
          ["„Ich koche gern,", "“Eu gosto de cozinhar,", "ich|kochen|gern"],
          ["ich bin ruhig,", "sou uma pessoa tranquila", "ich|sein|ruhig"],
          ["und ich bringe Kuchen mit.“", "e levo bolo.”", "und|ich|mitbringen|Kuchen"],
          ["In vier Wochen", "Daqui a quatro semanas", "in|vier|Woche"],
          ["beginnt die Suche wieder.", "a busca começa de novo.", "beginnen|der|wieder"],
          ["Aber diesmal", "Mas desta vez", "aber"],
          ["hast du Zeit.", "você tem tempo.", "haben|du|Zeit"]]]
      ],
      fim: { tipo: "neutro", titulo: "Um mês de fôlego" }
    },

    f_prazo: {
      cap: "Seis semanas",
      p: [
        ["Am Montag um acht Uhr sitzt du im Bürgeramt, ohne Bestätigung. Die Frau am Schalter ist freundlich, aber hart. „Dann brauchen Sie einen neuen Termin.“ Sie schaut auf ihren Bildschirm. „Der nächste freie Termin ist in sechs Wochen.“",
         "Na segunda, às oito horas, você está no Bürgeramt, sem confirmação. A mulher no guichê é simpática, mas firme. “Então você precisa de um novo horário.” Ela olha para a tela. “O próximo horário livre é daqui a seis semanas.”",
         [["Am Montag um acht Uhr", "Na segunda, às oito horas,", "an|der|Montag|um|acht|Uhr"],
          ["sitzt du im Bürgeramt,", "você está no Bürgeramt,", "sitzen|du|in|der"],
          ["ohne Bestätigung.", "sem confirmação.", "ohne"],
          ["Die Frau am Schalter", "A mulher no guichê", "der|Frau|an|der"],
          ["ist freundlich,", "é simpática,", "sein|freundlich"],
          ["aber hart.", "mas firme.", "aber"],
          ["„Dann brauchen Sie", "“Então você precisa de", "dann|brauchen|sie"],
          ["einen neuen Termin.“", "um novo horário.”", "ein|neu|Termin"],
          ["Sie schaut", "Ela olha", "sie|schauen"],
          ["auf ihren Bildschirm.", "para a tela.", "auf|ihr|Bildschirm"],
          ["„Der nächste freie Termin", "“O próximo horário livre", "der|nächste|frei|Termin"],
          ["ist in sechs Wochen.“", "é daqui a seis semanas.”", "sein|in|sechs|Woche"]]],
        ["Sechs Wochen ohne Konto. Dein neuer Chef schreibt eine kurze E-Mail: „Ohne Konto können wir leider nicht zahlen.“ Am Abend sitzt du wieder im Hostel, zwischen elf fremden Leuten. Auf deinem Handy ist eine neue Anzeige. Sehr schön. Sehr billig.",
         "Seis semanas sem conta. Seu novo chefe escreve um e-mail curto: “Sem conta, infelizmente não podemos pagar.” À noite você está de novo no hostel, entre onze desconhecidos. No seu celular há um novo anúncio. Muito bonito. Muito barato.",
         [["Sechs Wochen ohne Konto.", "Seis semanas sem conta.", "sechs|Woche|ohne|Konto"],
          ["Dein neuer Chef", "Seu novo chefe", "dein|neu|Chef"],
          ["schreibt eine kurze E-Mail:", "escreve um e-mail curto:", "schreiben|ein|kurz|E-Mail"],
          ["„Ohne Konto", "“Sem conta,", "ohne|Konto"],
          ["können wir leider nicht zahlen.“", "infelizmente não podemos pagar.”", "können|wir|leider|nicht|zahlen"],
          ["Am Abend sitzt du", "À noite você está", "an|der|Abend|sitzen|du"],
          ["wieder im Hostel,", "de novo no hostel,", "wieder|in|der"],
          ["zwischen elf fremden Leuten.", "entre onze desconhecidos.", "zwischen|elf|fremd|Leute"],
          ["Auf deinem Handy", "No seu celular", "auf|dein|Handy"],
          ["ist eine neue Anzeige.", "há um novo anúncio.", "sein|ein|neu"],
          ["Sehr schön.", "Muito bonito.", "sehr|schön"],
          ["Sehr billig.", "Muito barato.", "sehr|billig"]]]
      ],
      fim: { tipo: "ruim", titulo: "Prazo perdido" }
    },

    f_mentira: {
      cap: "Fumaça demais",
      p: [
        ["„Nicht meine“, sagt Tobias ruhig. „Ich rauche eine andere Marke.“ Stille. Lena schaut ihn an: „Du rauchst?“ Dann schaut sie dich an. Frau Huber stellt ihre Tasse auf den Tisch. „Ich habe gesagt: keine Geschichten.“",
         "“Não é meu”, diz Tobias, calmo. “Eu fumo outra marca.” Silêncio. Lena olha para ele: “Você fuma?” Depois olha para você. A senhora Huber coloca a xícara na mesa. “Eu disse: nada de histórias.”",
         [["„Nicht meine“,", "“Não é meu”,", "nicht|mein"],
          ["sagt Tobias ruhig.", "diz Tobias, calmo.", "sagen|ruhig"],
          ["„Ich rauche", "“Eu fumo", "ich|rauchen"],
          ["eine andere Marke.“", "outra marca.”", "ein|ander"],
          ["Stille.", "Silêncio.", ""],
          ["Lena schaut ihn an:", "Lena olha para ele:", "schauen|er"],
          ["„Du rauchst?“", "“Você fuma?”", "du|rauchen"],
          ["Dann schaut sie dich an.", "Depois olha para você.", "dann|schauen|sie|du"],
          ["Frau Huber stellt", "A senhora Huber coloca", "Frau|stellen"],
          ["ihre Tasse auf den Tisch.", "a xícara na mesa.", "ihr|Tasse|auf|der|Tisch"],
          ["„Ich habe gesagt:", "“Eu disse:", "ich|haben|sagen"],
          ["keine Geschichten.“", "nada de histórias.”", "kein|Geschichte"]]],
        ["Zehn Minuten später stehst du wieder vor dem Haus. Das Zimmer bekommt eine Studentin mit einer Excel-Tabelle. Am Montag hast du keine Bestätigung und einen neuen Termin in sechs Wochen. Tobias schreibt dir am Abend: „Danke. Jetzt rauche ich im Park.“",
         "Dez minutos depois você está de novo na frente do prédio. Quem fica com o quarto é uma estudante com uma planilha de Excel. Na segunda você não tem confirmação e ganha um novo horário daqui a seis semanas. Tobias te escreve à noite: “Valeu. Agora eu fumo no parque.”",
         [["Zehn Minuten später", "Dez minutos depois", "zehn|Minute|später"],
          ["stehst du wieder", "você está de novo", "stehen|du|wieder"],
          ["vor dem Haus.", "na frente do prédio.", "vor|der|Haus"],
          ["Das Zimmer bekommt", "Quem fica com o quarto é", "der|Zimmer|bekommen"],
          ["eine Studentin", "uma estudante", "ein|Student"],
          ["mit einer Excel-Tabelle.", "com uma planilha de Excel.", "mit|ein"],
          ["Am Montag", "Na segunda", "an|der|Montag"],
          ["hast du keine Bestätigung", "você não tem confirmação", "haben|du|kein"],
          ["und einen neuen Termin", "e ganha um novo horário", "und|ein|neu|Termin"],
          ["in sechs Wochen.", "daqui a seis semanas.", "in|sechs|Woche"],
          ["Tobias schreibt dir", "Tobias te escreve", "schreiben|du"],
          ["am Abend:", "à noite:", "an|der|Abend"],
          ["„Danke.", "“Valeu.", "danke"],
          ["Jetzt rauche ich im Park.“", "Agora eu fumo no parque.”", "jetzt|rauchen|ich|in|der|Park"]]]
      ],
      fim: { tipo: "ruim", titulo: "Fumaça demais" }
    }
  }
});
