VB_HIST.de.push({
  id: "trem-noturno",
  titulo: "Trem noturno",
  genero: "Suspense",
  nivel: "A2",
  desc: "No trem noturno de Viena a Hamburgo, sua bolsa é trocada por uma idêntica, com um envelope lacrado e um celular que não para de tocar.",
  inicio: "c1",
  cenas: {
    c1: {
      cap: "Partida de Viena",
      p: [
        ["Es ist zehn Uhr abends. In Wien steigst du in den Nachtzug nach Hamburg. Deinen Koffer stellst du unter das Bett, deine schwarze Tasche legst du nach oben. Der Schaffner, Herr Ölmez, prüft schnell deine Fahrkarte und geht weiter.",
         "São dez da noite. Em Viena, você sobe no trem noturno para Hamburgo. Você coloca a mala embaixo da cama e põe sua bolsa preta lá em cima. O condutor, o senhor Ölmez, confere rápido sua passagem e segue em frente.",
         [["Es ist zehn Uhr abends.", "São dez da noite.", "es|sein|zehn|Uhr"],
          ["In Wien", "Em Viena,", "in"],
          ["steigst du", "você sobe", "steigen|du"],
          ["in den Nachtzug", "no trem noturno", "in|der"],
          ["nach Hamburg.", "para Hamburgo.", "nach"],
          ["Deinen Koffer", "Sua mala", "dein|Koffer"],
          ["stellst du unter das Bett,", "você coloca embaixo da cama,", "stellen|du|unter|der|Bett"],
          ["deine schwarze Tasche", "sua bolsa preta", "dein|schwarz|Tasche"],
          ["legst du nach oben.", "você põe lá em cima.", "legen|du|nach|oben"],
          ["Der Schaffner, Herr Ölmez,", "O condutor, o senhor Ölmez,", "der|Herr"],
          ["prüft schnell deine Fahrkarte", "confere rápido sua passagem", "prüfen|schnell|dein|Fahrkarte"],
          ["und geht weiter.", "e segue em frente.", "und|gehen"]]],
        ["Du schläfst kurz ein. Später nimmst du deine Tasche und machst sie auf. Sie sieht genau gleich aus, aber darin sind nicht deine Sachen. Da liegen nur ein geschlossener Umschlag und ein fremdes Handy. Dann klingelt das Handy.",
         "Você cochila um pouco. Mais tarde, pega sua bolsa e a abre. Ela parece exatamente igual, mas dentro não estão as suas coisas. Há só um envelope lacrado e o celular de outra pessoa. Então o celular toca.",
         [["Du schläfst kurz ein.", "Você cochila um pouco.", "du|einschlafen|kurz"],
          ["Später nimmst du deine Tasche", "Mais tarde, você pega sua bolsa", "später|nehmen|du|dein|Tasche"],
          ["und machst sie auf.", "e a abre.", "und|aufmachen|sie"],
          ["Sie sieht genau gleich aus,", "Ela parece exatamente igual,", "sie|aussehen|genau|gleich"],
          ["aber darin", "mas dentro", "aber"],
          ["sind nicht deine Sachen.", "não estão as suas coisas.", "sein|nicht|dein|Sache"],
          ["Da liegen nur", "Há só", "da|liegen|nur"],
          ["ein geschlossener Umschlag", "um envelope lacrado", "ein|geschlossen"],
          ["und ein fremdes Handy.", "e o celular de outra pessoa.", "und|ein|fremd|Handy"],
          ["Dann klingelt das Handy.", "Então o celular toca.", "dann|klingeln|der|Handy"]]]
      ],
      escolhas: [
        { pt: "Atender o celular.", de: "Den Anruf annehmen.", ir: "c2a", marca: "telefon" },
        { pt: "Deixar tocar e abrir o envelope.", de: "Es klingeln lassen und den Umschlag öffnen.", ir: "c2b", marca: "umschlag" }
      ]
    },

    c2a: {
      cap: "A voz",
      p: [
        ["Du nimmst den Anruf an. „Wer ist da?“, fragt ein Mann. Seine Stimme ist ruhig und freundlich. Ohne nachzudenken, sagst du deinen Namen. „Danke“, sagt er. „Hören Sie gut zu. Diese Tasche gehört mir.“",
         "Você atende a ligação. “Quem fala?”, pergunta um homem. A voz dele é calma e simpática. Sem pensar, você diz seu nome. “Obrigado”, diz ele. “Escute bem. Esta bolsa é minha.”",
         [["Du nimmst den Anruf an.", "Você atende a ligação.", "du|annehmen|der"],
          ["„Wer ist da?“,", "“Quem fala?”,", "wer|sein|da"],
          ["fragt ein Mann.", "pergunta um homem.", "fragen|ein|Mann"],
          ["Seine Stimme ist", "A voz dele é", "sein|Stimme"],
          ["ruhig und freundlich.", "calma e simpática.", "ruhig|und|freundlich"],
          ["Ohne nachzudenken,", "Sem pensar,", "ohne"],
          ["sagst du deinen Namen.", "você diz seu nome.", "sagen|du|dein|Name"],
          ["„Danke“, sagt er.", "“Obrigado”, diz ele.", "danke|sagen|er"],
          ["„Hören Sie gut zu.", "“Escute bem.", "hören|sie|gut"],
          ["Diese Tasche gehört mir.“", "Esta bolsa é minha.”", "dieser|Tasche|gehören|ich"]]],
        ["„Eine Frau im grauen Mantel ist auch im Zug. Sie will die Tasche haben. Geben Sie sie bitte niemandem. Ich finde Sie.“ Dann ist die Leitung tot. Du sitzt still da und hörst nur den Zug. Er weiß jetzt, wie du heißt.",
         "“Uma mulher de casaco cinza também está no trem. Ela quer a bolsa. Por favor, não a entregue a ninguém. Eu vou encontrar você.” Então a linha fica muda. Você fica ali em silêncio e só ouve o trem. Agora ele sabe como você se chama.",
         [["„Eine Frau", "“Uma mulher", "ein|Frau"],
          ["im grauen Mantel", "de casaco cinza", "in|der|grau|Mantel"],
          ["ist auch im Zug.", "também está no trem.", "sein|auch|in|der|Zug"],
          ["Sie will die Tasche haben.", "Ela quer a bolsa.", "sie|wollen|der|Tasche|haben"],
          ["Geben Sie sie bitte niemandem.", "Por favor, não a entregue a ninguém.", "geben|sie|bitte|niemand"],
          ["Ich finde Sie.“", "Eu vou encontrar você.”", "ich|finden|sie"],
          ["Dann ist die Leitung tot.", "Então a linha fica muda.", "dann|sein|der"],
          ["Du sitzt still da", "Você fica ali em silêncio", "du|sitzen|da"],
          ["und hörst nur den Zug.", "e só ouve o trem.", "und|hören|nur|der|Zug"],
          ["Er weiß jetzt,", "Agora ele sabe", "er|wissen|jetzt"],
          ["wie du heißt.", "como você se chama.", "wie|du|heißen"]]]
      ],
      escolhas: [
        { pt: "Procurar a mulher de casaco cinza.", de: "Die Frau im grauen Mantel suchen.", ir: "c3k" },
        { pt: "Esperar o homem na cabine.", de: "Im Abteil auf den Mann warten.", ir: "c3b" }
      ]
    },

    c2b: {
      cap: "O envelope",
      p: [
        ["Du lässt das Handy klingeln. Nach einer Minute ist es still. Du öffnest vorsichtig den Umschlag. Darin sind ein Brief und viele Kopien mit Zahlen. Oben auf dem Brief steht: „Landgericht Hamburg. Zeugin: Katrin Vogel. Termin: Montag, neun Uhr.“",
         "Você deixa o celular tocar. Depois de um minuto, tudo fica em silêncio. Você abre o envelope com cuidado. Dentro há uma carta e muitas cópias com números. No alto da carta está escrito: “Tribunal Estadual de Hamburgo. Testemunha: Katrin Vogel. Audiência: segunda-feira, nove horas.”",
         [["Du lässt das Handy klingeln.", "Você deixa o celular tocar.", "du|lassen|der|Handy|klingeln"],
          ["Nach einer Minute", "Depois de um minuto,", "nach|ein|Minute"],
          ["ist es still.", "tudo fica em silêncio.", "sein|es"],
          ["Du öffnest vorsichtig den Umschlag.", "Você abre o envelope com cuidado.", "du|öffnen|der"],
          ["Darin sind ein Brief", "Dentro há uma carta", "sein|ein|Brief"],
          ["und viele Kopien mit Zahlen.", "e muitas cópias com números.", "und|viele|mit|Zahl"],
          ["Oben auf dem Brief steht:", "No alto da carta está escrito:", "oben|auf|der|Brief|stehen"],
          ["„Landgericht Hamburg.", "“Tribunal Estadual de Hamburgo.", ""],
          ["Zeugin: Katrin Vogel.", "Testemunha: Katrin Vogel.", ""],
          ["Termin: Montag, neun Uhr.“", "Audiência: segunda-feira, nove horas.”", "Termin|Montag|neun|Uhr"]]],
        ["Unter dem Brief liegt ein Foto. Eine Frau mit kurzen Haaren und einem grauen Mantel. Du kennst das Gesicht. In Wien war sie am Bahnsteig direkt neben dir. Hat sie die Taschen getauscht? Oder hat jemand ihre Tasche gestohlen?",
         "Embaixo da carta há uma foto. Uma mulher de cabelo curto e casaco cinza. Você conhece esse rosto. Em Viena, ela estava na plataforma, bem ao seu lado. Ela trocou as bolsas? Ou alguém roubou a bolsa dela?",
         [["Unter dem Brief", "Embaixo da carta", "unter|der|Brief"],
          ["liegt ein Foto.", "há uma foto.", "liegen|ein|Foto"],
          ["Eine Frau", "Uma mulher", "ein|Frau"],
          ["mit kurzen Haaren", "de cabelo curto", "mit|kurz|Haar"],
          ["und einem grauen Mantel.", "e casaco cinza.", "und|ein|grau|Mantel"],
          ["Du kennst das Gesicht.", "Você conhece esse rosto.", "du|kennen|der|Gesicht"],
          ["In Wien war sie", "Em Viena, ela estava", "in|sein|sie"],
          ["am Bahnsteig", "na plataforma,", "an|der"],
          ["direkt neben dir.", "bem ao seu lado.", "neben|du"],
          ["Hat sie die Taschen getauscht?", "Ela trocou as bolsas?", "haben|sie|der|Tasche|tauschen"],
          ["Oder hat jemand", "Ou alguém", "oder|haben|jemand"],
          ["ihre Tasche gestohlen?", "roubou a bolsa dela?", "Tasche"]]]
      ],
      escolhas: [
        { pt: "Procurar Katrin Vogel no trem.", de: "Katrin Vogel im Zug suchen.", ir: "c3k" },
        { pt: "Guardar o envelope e esperar na cabine.", de: "Den Umschlag einstecken und im Abteil warten.", ir: "c3b" }
      ]
    },

    c3k: {
      cap: "Casaco cinza",
      p: [
        ["Im Speisewagen sitzt eine Frau im grauen Mantel allein am Fenster. Vor ihr steht ein Tee, aber sie trinkt nicht. Als sie die Tasche sieht, steht sie sofort auf. „Das ist meine Tasche“, sagt sie leise. „Ich heiße Katrin. Bitte geben Sie sie mir.“",
         "No vagão-restaurante, uma mulher de casaco cinza está sentada sozinha, perto da janela. Na frente dela há um chá, mas ela não bebe. Quando ela vê a bolsa, se levanta na hora. “Essa bolsa é minha”, diz ela, baixinho. “Meu nome é Katrin. Por favor, me dê a bolsa.”",
         [["Im Speisewagen", "No vagão-restaurante,", "in|der"],
          ["sitzt eine Frau", "está sentada uma mulher", "sitzen|ein|Frau"],
          ["im grauen Mantel", "de casaco cinza", "in|der|grau|Mantel"],
          ["allein am Fenster.", "sozinha, perto da janela.", "allein|an|der|Fenster"],
          ["Vor ihr steht ein Tee,", "Na frente dela há um chá,", "vor|sie|stehen|ein|Tee"],
          ["aber sie trinkt nicht.", "mas ela não bebe.", "aber|sie|trinken|nicht"],
          ["Als sie die Tasche sieht,", "Quando ela vê a bolsa,", "als|sie|der|Tasche|sehen"],
          ["steht sie sofort auf.", "ela se levanta na hora.", "aufstehen|sie|sofort"],
          ["„Das ist meine Tasche“,", "“Essa bolsa é minha”,", "das|sein|mein|Tasche"],
          ["sagt sie leise.", "diz ela, baixinho.", "sagen|sie|leise"],
          ["„Ich heiße Katrin.", "“Meu nome é Katrin.", "ich|heißen"],
          ["Bitte geben Sie sie mir.“", "Por favor, me dê a bolsa.”", "bitte|geben|sie|ich"]]],
        ["„Und wo ist meine Tasche?“, fragst du. „In meinem Abteil. Wir haben die Taschen in Wien verwechselt.“ Sie sieht immer wieder zur Tür. Sie hält die Tasse mit beiden Händen. Warum hat sie so viel Angst?",
         "“E onde está a minha bolsa?”, você pergunta. “Na minha cabine. Nós trocamos as bolsas sem querer em Viena.” Ela olha sem parar para a porta. Ela segura a xícara com as duas mãos. Por que ela tem tanto medo?",
         [["„Und wo ist meine Tasche?“,", "“E onde está a minha bolsa?”,", "und|wo|sein|mein|Tasche"],
          ["fragst du.", "você pergunta.", "fragen|du"],
          ["„In meinem Abteil.", "“Na minha cabine.", "in|mein"],
          ["Wir haben die Taschen", "Nós trocamos as bolsas", "wir|haben|der|Tasche"],
          ["in Wien verwechselt.“", "sem querer em Viena.”", "in"],
          ["Sie sieht immer wieder", "Ela olha sem parar", "sie|sehen|immer|wieder"],
          ["zur Tür.", "para a porta.", "zu|der|Tür"],
          ["Sie hält die Tasse", "Ela segura a xícara", "sie|halten|der|Tasse"],
          ["mit beiden Händen.", "com as duas mãos.", "mit|Hand"],
          ["Warum hat sie", "Por que ela tem", "warum|haben|sie"],
          ["so viel Angst?", "tanto medo?", "so|viel|Angst"]]]
      ],
      escolhas: [
        { pt: "Entregar a bolsa a ela agora.", de: "Ihr die Tasche sofort geben.", ir: "f_twist" },
        { pt: "Recusar e guardar a bolsa até Hamburgo.", de: "Nein sagen und die Tasche bis Hamburg behalten.", ir: "c4h" },
        { pt: "Testá-la: perguntar o que diz a carta do envelope.", de: "Fragen, was im Brief steht.", ir: "c4v", req: "umschlag" }
      ]
    },

    c3b: {
      cap: "Um homem educado",
      p: [
        ["Jemand klopft an die Tür. Ein Mann in einem teuren Anzug steht im Gang und lächelt. „Guten Abend. Wir kennen uns nicht, mein Name ist Brandt.“ Er zeigt auf die schwarze Tasche. „Ich glaube, die gehört mir.“",
         "Alguém bate na porta. Um homem de terno caro está no corredor e sorri. “Boa noite. A gente não se conhece, meu nome é Brandt.” Ele aponta para a bolsa preta. “Acho que ela é minha.”",
         [["Jemand klopft an die Tür.", "Alguém bate na porta.", "jemand|klopfen|an|der|Tür"],
          ["Ein Mann", "Um homem", "ein|Mann"],
          ["in einem teuren Anzug", "de terno caro", "in|ein|teuer"],
          ["steht im Gang", "está no corredor", "stehen|in|der"],
          ["und lächelt.", "e sorri.", "und"],
          ["„Guten Abend.", "“Boa noite.", "gut|Abend"],
          ["Wir kennen uns nicht,", "A gente não se conhece,", "wir|kennen|nicht"],
          ["mein Name ist Brandt.“", "meu nome é Brandt.”", "mein|Name|sein"],
          ["Er zeigt", "Ele aponta", "er|zeigen"],
          ["auf die schwarze Tasche.", "para a bolsa preta.", "auf|der|schwarz|Tasche"],
          ["„Ich glaube,", "“Acho", "ich|glauben"],
          ["die gehört mir.“", "que ela é minha.”", "der|gehören|ich"]]],
        ["Er gibt dir eine Visitenkarte: „Brandt, Sicherheit, Nordwerk GmbH“. „Eine frühere Mitarbeiterin hat Dokumente aus unserer Firma gestohlen. Sie sind in diesem Umschlag. Ich bezahle Ihnen gern zweihundert Euro für Ihre Hilfe.“ Er spricht höflich, aber seine Augen sind kalt.",
         "Ele te dá um cartão de visita: “Brandt, Segurança, Nordwerk Ltda.”. “Uma ex-funcionária roubou documentos da nossa empresa. Eles estão neste envelope. Pago com prazer duzentos euros pela sua ajuda.” Ele fala com educação, mas os olhos dele são frios.",
         [["Er gibt dir", "Ele te dá", "er|geben|du"],
          ["eine Visitenkarte:", "um cartão de visita:", "ein"],
          ["„Brandt, Sicherheit, Nordwerk GmbH“.", "“Brandt, Segurança, Nordwerk Ltda.”.", "Sicherheit"],
          ["„Eine frühere Mitarbeiterin", "“Uma ex-funcionária", "ein"],
          ["hat Dokumente", "roubou documentos", "haben"],
          ["aus unserer Firma gestohlen.", "da nossa empresa.", "aus|unser|Firma"],
          ["Sie sind in diesem Umschlag.", "Eles estão neste envelope.", "sie|sein|in|dieser"],
          ["Ich bezahle Ihnen gern", "Pago com prazer", "ich|bezahlen|sie|gern"],
          ["zweihundert Euro", "duzentos euros", "Euro"],
          ["für Ihre Hilfe.“", "pela sua ajuda.”", "für|Hilfe"],
          ["Er spricht höflich,", "Ele fala com educação,", "er|sprechen"],
          ["aber seine Augen sind kalt.", "mas os olhos dele são frios.", "aber|sein|Auge|kalt"]]]
      ],
      escolhas: [
        { pt: "Aceitar o dinheiro e entregar a bolsa.", de: "Das Geld nehmen und ihm die Tasche geben.", ir: "c4b" },
        { pt: "Dizer que só a polícia vai receber a bolsa.", de: "Sagen, dass nur die Polizei die Tasche bekommt.", ir: "c4h" },
        { pt: "Você reconhece a voz do telefone: ele está mentindo. Ir procurar a mulher.", de: "Die Stimme erkennen und die Frau suchen.", ir: "c4v", req: "telefon" }
      ]
    },

    c4v: {
      cap: "A verdade de Katrin",
      p: [
        ["Du erzählst Katrin, was du weißt. Sie schweigt einen Moment. Dann sagt sie leise: „Ich habe acht Jahre bei Nordwerk gearbeitet. Seit Jahren zahlt die Firma keine Steuern. Am Montag spreche ich vor Gericht. Herr Brandt soll das verhindern.“",
         "Você conta a Katrin o que sabe. Ela fica calada por um momento. Então diz baixinho: “Eu trabalhei oito anos na Nordwerk. Há anos a empresa não paga impostos. Na segunda-feira, eu falo no tribunal. O senhor Brandt deve impedir isso.”",
         [["Du erzählst Katrin,", "Você conta a Katrin", "du|erzählen"],
          ["was du weißt.", "o que sabe.", "was|du|wissen"],
          ["Sie schweigt einen Moment.", "Ela fica calada por um momento.", "sie|schweigen|ein|Moment"],
          ["Dann sagt sie leise:", "Então ela diz baixinho:", "dann|sagen|sie|leise"],
          ["„Ich habe acht Jahre", "“Eu trabalhei oito anos", "ich|haben|acht|Jahr"],
          ["bei Nordwerk gearbeitet.", "na Nordwerk.", "bei|arbeiten"],
          ["Seit Jahren zahlt die Firma", "Há anos a empresa não paga", "seit|Jahr|zahlen|der|Firma"],
          ["keine Steuern.", "impostos.", "kein|Steuer"],
          ["Am Montag", "Na segunda-feira,", "an|der|Montag"],
          ["spreche ich vor Gericht.", "eu falo no tribunal.", "sprechen|ich|vor|Gericht"],
          ["Herr Brandt soll", "O senhor Brandt deve", "Herr|sollen"],
          ["das verhindern.“", "impedir isso.”", "das"]]],
        ["In diesem Moment öffnet sich die Tür. Herr Brandt kommt herein, setzt sich an einen Tisch und bestellt einen Kaffee. Er sieht euch nicht an. Katrin sagt sehr leise: „Er wartet, bis ich schlafe. Was machen wir jetzt?“",
         "Nesse momento, a porta se abre. O senhor Brandt entra, senta-se a uma mesa e pede um café. Ele não olha para vocês. Katrin diz bem baixinho: “Ele está esperando eu dormir. O que a gente faz agora?”",
         [["In diesem Moment", "Nesse momento,", "in|dieser|Moment"],
          ["öffnet sich die Tür.", "a porta se abre.", "öffnen|sich|der|Tür"],
          ["Herr Brandt kommt herein,", "O senhor Brandt entra,", "Herr|kommen"],
          ["setzt sich", "senta-se", "setzen|sich"],
          ["an einen Tisch", "a uma mesa", "an|ein|Tisch"],
          ["und bestellt einen Kaffee.", "e pede um café.", "und|bestellen|ein|Kaffee"],
          ["Er sieht euch nicht an.", "Ele não olha para vocês.", "er|sehen|ihr|nicht"],
          ["Katrin sagt sehr leise:", "Katrin diz bem baixinho:", "sagen|sehr|leise"],
          ["„Er wartet,", "“Ele está esperando", "er|warten"],
          ["bis ich schlafe.", "eu dormir.", "bis|ich|schlafen"],
          ["Was machen wir jetzt?“", "O que a gente faz agora?”", "was|machen|wir|jetzt"]]]
      ],
      escolhas: [
        { pt: "Ir com Katrin até o condutor, o senhor Ölmez.", de: "Mit Katrin zum Schaffner gehen.", ir: "c5s" },
        { pt: "Guardar a bolsa com você até Hamburgo, longe de Brandt.", de: "Die Tasche bis Hamburg bei sich behalten.", ir: "c5h" }
      ]
    },

    c4h: {
      cap: "A noite longa",
      p: [
        ["Du gehst zurück in dein Abteil und schließt die Tür ab. Die Tasche liegt neben dir auf dem Bett. Du schläfst nicht. Um drei Uhr bewegt sich die Türklinke langsam nach unten. Jemand versucht, die Tür zu öffnen.",
         "Você volta para a sua cabine e tranca a porta. A bolsa está ao seu lado, na cama. Você não dorme. Às três horas, a maçaneta se move devagar para baixo. Alguém tenta abrir a porta.",
         [["Du gehst zurück", "Você volta", "du|gehen|zurück"],
          ["in dein Abteil", "para a sua cabine", "in|dein"],
          ["und schließt die Tür ab.", "e tranca a porta.", "und|schließen|der|Tür"],
          ["Die Tasche liegt", "A bolsa está", "der|Tasche|liegen"],
          ["neben dir auf dem Bett.", "ao seu lado, na cama.", "neben|du|auf|der|Bett"],
          ["Du schläfst nicht.", "Você não dorme.", "du|schlafen|nicht"],
          ["Um drei Uhr", "Às três horas,", "um|drei|Uhr"],
          ["bewegt sich die Türklinke", "a maçaneta se move", "sich"],
          ["langsam nach unten.", "devagar para baixo.", "langsam|nach|unten"],
          ["Jemand versucht,", "Alguém tenta", "jemand|versuchen"],
          ["die Tür zu öffnen.", "abrir a porta.", "der|Tür|zu|öffnen"]]],
        ["Dann ist es wieder still. In der Tasche klingelt das Handy. Du antwortest nicht. Der Zug wird langsamer und hält an einem kleinen Bahnhof. Draußen ist alles dunkel, nur eine Lampe brennt. Die Türen gehen auf.",
         "Depois, tudo fica em silêncio de novo. Na bolsa, o celular toca. Você não atende. O trem fica mais lento e para numa estação pequena. Lá fora está tudo escuro, só uma lâmpada está acesa. As portas se abrem.",
         [["Dann ist es wieder still.", "Depois, tudo fica em silêncio de novo.", "dann|sein|es|wieder"],
          ["In der Tasche", "Na bolsa,", "in|der|Tasche"],
          ["klingelt das Handy.", "o celular toca.", "klingeln|der|Handy"],
          ["Du antwortest nicht.", "Você não atende.", "du|antworten|nicht"],
          ["Der Zug wird langsamer", "O trem fica mais lento", "der|Zug|werden|langsam"],
          ["und hält", "e para", "und|halten"],
          ["an einem kleinen Bahnhof.", "numa estação pequena.", "an|ein|klein|Bahnhof"],
          ["Draußen ist alles dunkel,", "Lá fora está tudo escuro,", "draußen|sein|alles|dunkel"],
          ["nur eine Lampe brennt.", "só uma lâmpada está acesa.", "nur|ein|Lampe|brennen"],
          ["Die Türen gehen auf.", "As portas se abrem.", "der|Tür|gehen"]]]
      ],
      escolhas: [
        { pt: "Descer aqui com a bolsa, antes que seja tarde.", de: "Mit der Tasche hier aussteigen.", ir: "f_estacao" },
        { pt: "Ficar na cabine até Hamburgo.", de: "Bis Hamburg im Abteil bleiben.", ir: "c5h" }
      ]
    },

    c4b: {
      cap: "Duzentos euros",
      p: [
        ["Herr Brandt nimmt die Tasche und gibt dir vier Scheine zu fünfzig Euro. „Sie haben das Richtige getan“, sagt er und geht. Zehn Minuten später klopft es laut. Vor der Tür steht eine Frau im grauen Mantel. Ihr Gesicht ist ganz weiß.",
         "O senhor Brandt pega a bolsa e te dá quatro notas de cinquenta euros. “Você fez a coisa certa”, diz ele, e vai embora. Dez minutos depois, batem forte na porta. Na porta está uma mulher de casaco cinza. O rosto dela está todo branco.",
         [["Herr Brandt nimmt die Tasche", "O senhor Brandt pega a bolsa", "Herr|nehmen|der|Tasche"],
          ["und gibt dir", "e te dá", "und|geben|du"],
          ["vier Scheine", "quatro notas", "vier"],
          ["zu fünfzig Euro.", "de cinquenta euros.", "zu|Euro"],
          ["„Sie haben das Richtige getan“,", "“Você fez a coisa certa”,", "sie|haben|der|richtig|tun"],
          ["sagt er und geht.", "diz ele, e vai embora.", "sagen|er|und|gehen"],
          ["Zehn Minuten später", "Dez minutos depois,", "zehn|Minute|später"],
          ["klopft es laut.", "batem forte na porta.", "klopfen|es|laut"],
          ["Vor der Tür", "Na porta", "vor|der|Tür"],
          ["steht eine Frau", "está uma mulher", "stehen|ein|Frau"],
          ["im grauen Mantel.", "de casaco cinza.", "in|der|grau|Mantel"],
          ["Ihr Gesicht", "O rosto dela", "Gesicht"],
          ["ist ganz weiß.", "está todo branco.", "sein|ganz|weiß"]]],
        ["„Wo ist meine Tasche?“, fragt sie. Du zeigst ihr das Geld. Sie schließt die Augen. „Ich bin Katrin Vogel. Im Umschlag sind Beweise gegen Nordwerk. Am Montag bin ich Zeugin vor Gericht. Ohne die Papiere glaubt mir niemand.“",
         "“Onde está a minha bolsa?”, pergunta ela. Você mostra o dinheiro a ela. Ela fecha os olhos. “Eu sou Katrin Vogel. No envelope estão as provas contra a Nordwerk. Na segunda-feira, sou testemunha no tribunal. Sem os papéis, ninguém acredita em mim.”",
         [["„Wo ist meine Tasche?“,", "“Onde está a minha bolsa?”,", "wo|sein|mein|Tasche"],
          ["fragt sie.", "pergunta ela.", "fragen|sie"],
          ["Du zeigst ihr das Geld.", "Você mostra o dinheiro a ela.", "du|zeigen|sie|der|Geld"],
          ["Sie schließt die Augen.", "Ela fecha os olhos.", "sie|schließen|der|Auge"],
          ["„Ich bin Katrin Vogel.", "“Eu sou Katrin Vogel.", "ich|sein"],
          ["Im Umschlag", "No envelope", "in|der"],
          ["sind Beweise gegen Nordwerk.", "estão as provas contra a Nordwerk.", "sein|Beweis|gegen"],
          ["Am Montag", "Na segunda-feira,", "an|der|Montag"],
          ["bin ich Zeugin vor Gericht.", "sou testemunha no tribunal.", "sein|ich|vor|Gericht"],
          ["Ohne die Papiere", "Sem os papéis,", "ohne|der|Papier"],
          ["glaubt mir niemand.“", "ninguém acredita em mim.”", "glauben|ich|niemand"]]]
      ],
      escolhas: [
        { pt: "Chamar o condutor e ajudar Katrin.", de: "Den Schaffner holen und Katrin helfen.", ir: "c5s" },
        { pt: "Não se meter. Em Hamburgo, contar tudo à polícia.", de: "Nichts tun und in Hamburg zur Polizei gehen.", ir: "f_polizei" }
      ]
    },

    c5s: {
      cap: "O condutor",
      p: [
        ["Herr Ölmez sitzt in seinem kleinen Dienstabteil, zwischen Fahrkarten und Formularen. Er ist müde und hat viel zu tun. Aber er hört zu, ohne euch zu unterbrechen. Katrin zeigt ihm ihren Ausweis und einen Brief vom Gericht.",
         "O senhor Ölmez está sentado na sua pequena cabine de serviço, entre passagens e formulários. Ele está cansado e tem muito trabalho. Mas ele escuta sem interromper vocês. Katrin mostra a ele a identidade dela e uma carta do tribunal.",
         [["Herr Ölmez sitzt", "O senhor Ölmez está sentado", "Herr|sitzen"],
          ["in seinem kleinen Dienstabteil,", "na sua pequena cabine de serviço,", "in|sein|klein"],
          ["zwischen Fahrkarten und Formularen.", "entre passagens e formulários.", "zwischen|Fahrkarte|und"],
          ["Er ist müde", "Ele está cansado", "er|sein|müde"],
          ["und hat viel zu tun.", "e tem muito trabalho.", "und|haben|viel|zu|tun"],
          ["Aber er hört zu,", "Mas ele escuta", "aber|er|hören"],
          ["ohne euch zu unterbrechen.", "sem interromper vocês.", "ohne|ihr|zu"],
          ["Katrin zeigt ihm", "Katrin mostra a ele", "zeigen|er"],
          ["ihren Ausweis", "a identidade dela", ""],
          ["und einen Brief vom Gericht.", "e uma carta do tribunal.", "und|ein|Brief|von|der|Gericht"]]],
        ["Dann nimmt er sein Telefon. „Ich rufe die Bundespolizei an. Beim nächsten großen Halt steigen zwei Polizisten ein. Bis dahin bleiben Sie hier bei mir.“ Durch das kleine Fenster siehst du Herrn Brandt im Gang. Er lächelt nicht mehr.",
         "Então ele pega o telefone. “Vou ligar para a polícia federal. Na próxima parada grande, entram dois policiais. Até lá, vocês ficam aqui comigo.” Pela janelinha, você vê o senhor Brandt no corredor. Ele não sorri mais.",
         [["Dann nimmt er sein Telefon.", "Então ele pega o telefone.", "dann|nehmen|er|sein|Telefon"],
          ["„Ich rufe die Bundespolizei an.", "“Vou ligar para a polícia federal.", "ich|anrufen|der"],
          ["Beim nächsten großen Halt", "Na próxima parada grande,", "bei|der|nächste|groß"],
          ["steigen zwei Polizisten ein.", "entram dois policiais.", "einsteigen|zwei"],
          ["Bis dahin", "Até lá,", "bis"],
          ["bleiben Sie hier bei mir.“", "vocês ficam aqui comigo.”", "bleiben|sie|hier|bei|ich"],
          ["Durch das kleine Fenster", "Pela janelinha,", "durch|der|klein|Fenster"],
          ["siehst du Herrn Brandt", "você vê o senhor Brandt", "sehen|du|Herr"],
          ["im Gang.", "no corredor.", "in|der"],
          ["Er lächelt nicht mehr.", "Ele não sorri mais.", "er|nicht|mehr"]]]
      ],
      escolhas: [
        { pt: "Ficar com Katrin e o senhor Ölmez.", de: "Bei Katrin und Herrn Ölmez bleiben.", ir: "f_bom" },
        { pt: "Sair dali e descer na próxima parada.", de: "Weggehen und beim nächsten Halt aussteigen.", ir: "f_estacao" }
      ]
    },

    c5h: {
      cap: "Hamburgo",
      p: [
        ["Um sieben Uhr hält der Zug in Hamburg. Du hast die ganze Nacht nicht geschlafen. Auf dem Bahnsteig stehen zwei Polizisten. Links wartet die Frau im grauen Mantel. Rechts steht ein Mann in einem teuren Anzug. Beide sehen dich an.",
         "Às sete horas, o trem para em Hamburgo. Você passou a noite inteira sem dormir. Na plataforma estão dois policiais. À esquerda, espera a mulher de casaco cinza. À direita, está um homem de terno caro. Os dois olham para você.",
         [["Um sieben Uhr", "Às sete horas,", "um|sieben|Uhr"],
          ["hält der Zug", "o trem para", "halten|der|Zug"],
          ["in Hamburg.", "em Hamburgo.", "in"],
          ["Du hast die ganze Nacht", "Você passou a noite inteira", "du|haben|der|ganz|Nacht"],
          ["nicht geschlafen.", "sem dormir.", "nicht|schlafen"],
          ["Auf dem Bahnsteig", "Na plataforma", "auf|der"],
          ["stehen zwei Polizisten.", "estão dois policiais.", "stehen|zwei"],
          ["Links wartet die Frau", "À esquerda, espera a mulher", "links|warten|der|Frau"],
          ["im grauen Mantel.", "de casaco cinza.", "in|der|grau|Mantel"],
          ["Rechts steht ein Mann", "À direita, está um homem", "rechts|stehen|ein|Mann"],
          ["in einem teuren Anzug.", "de terno caro.", "in|ein|teuer"],
          ["Beide sehen dich an.", "Os dois olham para você.", "sehen|du"]]],
        ["Die Tasche ist schwer in deiner Hand, obwohl sie fast leer ist. Der Mann hebt kurz die Hand, die Frau bewegt sich nicht. Du musst dich jetzt entscheiden.",
         "A bolsa pesa na sua mão, embora esteja quase vazia. O homem levanta rápido a mão, a mulher não se mexe. Você precisa decidir agora.",
         [["Die Tasche ist schwer", "A bolsa pesa", "der|Tasche|sein|schwer"],
          ["in deiner Hand,", "na sua mão,", "in|dein|Hand"],
          ["obwohl sie fast leer ist.", "embora esteja quase vazia.", "obwohl|sie|fast|leer|sein"],
          ["Der Mann hebt kurz", "O homem levanta rápido", "der|Mann|heben|kurz"],
          ["die Hand,", "a mão,", "der|Hand"],
          ["die Frau bewegt sich nicht.", "a mulher não se mexe.", "der|Frau|sich|nicht"],
          ["Du musst dich jetzt entscheiden.", "Você precisa decidir agora.", "du|müssen|jetzt|entscheiden"]]]
      ],
      escolhas: [
        { pt: "Ir até os policiais e contar tudo.", de: "Zu den Polizisten gehen und alles erzählen.", ir: "f_polizei" },
        { pt: "Entregar a bolsa à mulher de casaco cinza.", de: "Der Frau im grauen Mantel die Tasche geben.", ir: "f_twist" }
      ]
    },

    f_bom: {
      cap: "A testemunha",
      p: [
        ["Eine Stunde später steigen zwei Polizisten ein. Sie sprechen lange mit Herrn Brandt im Gang. Er bleibt höflich, aber am nächsten Bahnhof muss er mit ihnen aussteigen. Die schwarze Tasche ist wieder bei Katrin. Herr Ölmez bringt euch zwei Tassen Kaffee.",
         "Uma hora depois, entram dois policiais. Eles conversam muito tempo com o senhor Brandt no corredor. Ele continua educado, mas na próxima estação precisa descer com eles. A bolsa preta está de novo com Katrin. O senhor Ölmez traz para vocês duas xícaras de café.",
         [["Eine Stunde später", "Uma hora depois,", "ein|Stunde|später"],
          ["steigen zwei Polizisten ein.", "entram dois policiais.", "einsteigen|zwei"],
          ["Sie sprechen lange", "Eles conversam muito tempo", "sie|sprechen|lang"],
          ["mit Herrn Brandt im Gang.", "com o senhor Brandt no corredor.", "mit|Herr|in|der"],
          ["Er bleibt höflich,", "Ele continua educado,", "er|bleiben"],
          ["aber am nächsten Bahnhof", "mas na próxima estação", "aber|an|der|nächste|Bahnhof"],
          ["muss er mit ihnen aussteigen.", "precisa descer com eles.", "müssen|er|mit|sie|aussteigen"],
          ["Die schwarze Tasche", "A bolsa preta", "der|schwarz|Tasche"],
          ["ist wieder bei Katrin.", "está de novo com Katrin.", "sein|wieder|bei"],
          ["Herr Ölmez bringt euch", "O senhor Ölmez traz para vocês", "Herr|bringen|ihr"],
          ["zwei Tassen Kaffee.", "duas xícaras de café.", "zwei|Tasse|Kaffee"]]],
        ["In Hamburg scheint die Sonne. Katrin hält die Tasche mit beiden Händen fest. „Am Montag spreche ich vor Gericht“, sagt sie. „Und ich weiß jetzt: Man findet auch im Nachtzug Menschen, denen man vertrauen kann. Danke.“",
         "Em Hamburgo, faz sol. Katrin segura a bolsa firme com as duas mãos. “Na segunda-feira, eu falo no tribunal”, diz ela. “E agora eu sei: até num trem noturno a gente encontra pessoas em quem dá para confiar. Obrigada.”",
         [["In Hamburg", "Em Hamburgo,", "in"],
          ["scheint die Sonne.", "faz sol.", "scheinen|der|Sonne"],
          ["Katrin hält die Tasche", "Katrin segura a bolsa", "halten|der|Tasche"],
          ["mit beiden Händen fest.", "firme com as duas mãos.", "mit|Hand"],
          ["„Am Montag", "“Na segunda-feira,", "an|der|Montag"],
          ["spreche ich vor Gericht“,", "eu falo no tribunal”,", "sprechen|ich|vor|Gericht"],
          ["sagt sie.", "diz ela.", "sagen|sie"],
          ["„Und ich weiß jetzt:", "“E agora eu sei:", "und|ich|wissen|jetzt"],
          ["Man findet auch im Nachtzug", "até num trem noturno a gente encontra", "man|finden|auch|in|der"],
          ["Menschen,", "pessoas", "Mensch"],
          ["denen man vertrauen kann.", "em quem dá para confiar.", "man|vertrauen|können"],
          ["Danke.“", "Obrigada.”", "danke"]]]
      ],
      fim: { tipo: "bom", titulo: "A testemunha chega a Hamburgo" }
    },

    f_polizei: {
      cap: "Delegacia",
      p: [
        ["In Hamburg gehst du direkt zur Polizei. Du gibst ihnen alles, was du hast. Dann erzählst du vom Handy, vom Umschlag und von den zwei Fremden im Zug. Eine Polizistin schreibt alles auf. Das dauert zwei Stunden.",
         "Em Hamburgo, você vai direto à polícia. Você entrega a eles tudo o que tem. Depois, você fala do celular, do envelope e dos dois desconhecidos no trem. Uma policial anota tudo. Isso leva duas horas.",
         [["In Hamburg", "Em Hamburgo,", "in"],
          ["gehst du direkt", "você vai direto", "gehen|du"],
          ["zur Polizei.", "à polícia.", "zu|der|Polizei"],
          ["Du gibst ihnen alles,", "Você entrega a eles tudo", "du|geben|sie|alles"],
          ["was du hast.", "o que tem.", "was|du|haben"],
          ["Dann erzählst du", "Depois, você fala", "dann|erzählen|du"],
          ["vom Handy,", "do celular,", "von|der|Handy"],
          ["vom Umschlag", "do envelope", "von|der"],
          ["und von den zwei Fremden", "e dos dois desconhecidos", "und|von|der|zwei|fremd"],
          ["im Zug.", "no trem.", "in|der|Zug"],
          ["Eine Polizistin schreibt alles auf.", "Uma policial anota tudo.", "ein|schreiben|alles"],
          ["Das dauert zwei Stunden.", "Isso leva duas horas.", "das|zwei|Stunde"]]],
        ["Am Ende gibt sie dir eine Nummer für Fragen. „Wir melden uns“, sagt sie. Draußen scheint die Sonne. Die Frau im grauen Mantel und der Mann im Anzug sind weg. Du wirst nie erfahren, wie die Geschichte endet.",
         "No fim, ela te dá um número para dúvidas. “Nós entramos em contato”, diz ela. Lá fora, faz sol. A mulher de casaco cinza e o homem de terno sumiram. Você nunca vai saber como a história termina.",
         [["Am Ende", "No fim,", "an|der|Ende"],
          ["gibt sie dir", "ela te dá", "geben|sie|du"],
          ["eine Nummer für Fragen.", "um número para dúvidas.", "ein|Nummer|für|Frage"],
          ["„Wir melden uns“,", "“Nós entramos em contato”,", "wir"],
          ["sagt sie.", "diz ela.", "sagen|sie"],
          ["Draußen scheint die Sonne.", "Lá fora, faz sol.", "draußen|scheinen|der|Sonne"],
          ["Die Frau im grauen Mantel", "A mulher de casaco cinza", "der|Frau|in|der|grau|Mantel"],
          ["und der Mann im Anzug", "e o homem de terno", "und|der|Mann|in|der"],
          ["sind weg.", "sumiram.", "sein|weg"],
          ["Du wirst nie erfahren,", "Você nunca vai saber", "du|werden|nie"],
          ["wie die Geschichte endet.", "como a história termina.", "wie|der|Geschichte"]]]
      ],
      fim: { tipo: "neutro", titulo: "Nas mãos da polícia" }
    },

    f_estacao: {
      cap: "Estação sem nome",
      p: [
        ["Du steigst schnell aus. Hinter dir schließen sich die Türen, und der Zug fährt ohne dich weiter. Der Bahnhof ist leer und kalt. An der Wand hängt ein altes Schild, aber den Namen kannst du nicht lesen.",
         "Você desce depressa. Atrás de você, as portas se fecham, e o trem segue sem você. A estação está vazia e fria. Na parede há uma placa velha, mas o nome você não consegue ler.",
         [["Du steigst schnell aus.", "Você desce depressa.", "du|aussteigen|schnell"],
          ["Hinter dir", "Atrás de você,", "hinter|du"],
          ["schließen sich die Türen,", "as portas se fecham,", "schließen|sich|der|Tür"],
          ["und der Zug fährt", "e o trem segue", "und|der|Zug|fahren"],
          ["ohne dich weiter.", "sem você.", "ohne|du"],
          ["Der Bahnhof ist", "A estação está", "der|Bahnhof|sein"],
          ["leer und kalt.", "vazia e fria.", "leer|und|kalt"],
          ["An der Wand", "Na parede", "an|der|Wand"],
          ["hängt ein altes Schild,", "há uma placa velha,", "ein|alt"],
          ["aber den Namen", "mas o nome", "aber|der|Name"],
          ["kannst du nicht lesen.", "você não consegue ler.", "können|du|nicht|lesen"]]],
        ["Dein Koffer fährt nach Hamburg, dein Handy hat nur noch fünf Prozent. Du setzt dich auf eine kalte Bank und wartest auf den ersten Zug am Morgen. Du bist in Sicherheit, glaubst du. Aber du weißt nicht mehr, wem du glauben sollst.",
         "Sua mala vai para Hamburgo, seu celular tem só cinco por cento. Você se senta num banco frio e espera o primeiro trem da manhã. Você está em segurança, você acha. Mas você já não sabe em quem acreditar.",
         [["Dein Koffer fährt", "Sua mala vai", "dein|Koffer|fahren"],
          ["nach Hamburg,", "para Hamburgo,", "nach"],
          ["dein Handy hat", "seu celular tem", "dein|Handy|haben"],
          ["nur noch fünf Prozent.", "só cinco por cento.", "nur|noch|fünf|Prozent"],
          ["Du setzt dich", "Você se senta", "du|setzen"],
          ["auf eine kalte Bank", "num banco frio", "auf|ein|kalt|Bank"],
          ["und wartest", "e espera", "und|warten"],
          ["auf den ersten Zug", "o primeiro trem", "auf|der|erste|Zug"],
          ["am Morgen.", "da manhã.", "an|der|Morgen"],
          ["Du bist in Sicherheit,", "Você está em segurança,", "du|sein|in|Sicherheit"],
          ["glaubst du.", "você acha.", "glauben|du"],
          ["Aber du weißt nicht mehr,", "Mas você já não sabe", "aber|du|wissen|nicht|mehr"],
          ["wem du glauben sollst.", "em quem acreditar.", "wer|du|glauben|sollen"]]]
      ],
      fim: { tipo: "ruim", titulo: "Uma estação sem nome" }
    },

    f_twist: {
      cap: "A troca",
      p: [
        ["Die Frau im grauen Mantel nimmt die Tasche und sieht kurz hinein. Dann lächelt sie zum ersten Mal. Sie gibt dir eine andere schwarze Tasche: deine eigene. Nichts fehlt, nicht einmal dein Buch. „Entschuldigung“, sagt sie. „Ich habe die Taschen in Wien getauscht. Absichtlich.“",
         "A mulher de casaco cinza pega a bolsa e olha rápido dentro. Então ela sorri pela primeira vez. Ela te dá outra bolsa preta: a sua. Não falta nada, nem mesmo o seu livro. “Desculpe”, diz ela. “Eu troquei as bolsas em Viena. De propósito.”",
         [["Die Frau im grauen Mantel", "A mulher de casaco cinza", "der|Frau|in|der|grau|Mantel"],
          ["nimmt die Tasche", "pega a bolsa", "nehmen|der|Tasche"],
          ["und sieht kurz hinein.", "e olha rápido dentro.", "und|sehen|kurz"],
          ["Dann lächelt sie", "Então ela sorri", "dann|sie"],
          ["zum ersten Mal.", "pela primeira vez.", "zu|der|erste|mal"],
          ["Sie gibt dir", "Ela te dá", "sie|geben|du"],
          ["eine andere schwarze Tasche:", "outra bolsa preta:", "ein|ander|schwarz|Tasche"],
          ["deine eigene.", "a sua.", "dein|eigen"],
          ["Nichts fehlt,", "Não falta nada,", "nichts|fehlen"],
          ["nicht einmal dein Buch.", "nem mesmo o seu livro.", "nicht|dein|Buch"],
          ["„Entschuldigung“, sagt sie.", "“Desculpe”, diz ela.", "Entschuldigung|sagen|sie"],
          ["„Ich habe die Taschen", "“Eu troquei as bolsas", "ich|haben|der|Tasche"],
          ["in Wien getauscht.", "em Viena.", "in|tauschen"],
          ["Absichtlich.“", "De propósito.”", ""]]],
        ["„Ein Mann beobachtet mich seit Wien. Ich habe Sie gebraucht.“ Dann geht sie schnell weg, und nach einer Minute siehst du sie nicht mehr. Du hältst deine Tasche und verstehst langsam: Du hast etwas Wichtiges getragen, und niemand hat dich gefragt.",
         "“Um homem me vigia desde Viena. Eu precisei de você.” Então ela se afasta rápido, e depois de um minuto você não a vê mais. Você segura a sua bolsa e entende aos poucos: você carregou algo importante, e ninguém te perguntou nada.",
         [["„Ein Mann beobachtet mich", "“Um homem me vigia", "ein|Mann|beobachten|ich"],
          ["seit Wien.", "desde Viena.", "seit"],
          ["Ich habe Sie gebraucht.“", "Eu precisei de você.”", "ich|haben|sie|brauchen"],
          ["Dann geht sie schnell weg,", "Então ela se afasta rápido,", "dann|gehen|sie|schnell|weg"],
          ["und nach einer Minute", "e depois de um minuto", "und|nach|ein|Minute"],
          ["siehst du sie nicht mehr.", "você não a vê mais.", "sehen|du|sie|nicht|mehr"],
          ["Du hältst deine Tasche", "Você segura a sua bolsa", "du|halten|dein|Tasche"],
          ["und verstehst langsam:", "e entende aos poucos:", "und|verstehen|langsam"],
          ["Du hast etwas Wichtiges getragen,", "você carregou algo importante,", "du|haben|etwas|wichtig|tragen"],
          ["und niemand hat dich gefragt.", "e ninguém te perguntou nada.", "und|niemand|haben|du|fragen"]]]
      ],
      fim: { tipo: "neutro", titulo: "Você era o mensageiro" }
    }
  }
});
