VB_HIST.de.push({
  id: "velhos-amigos",
  titulo: "Velhos amigos",
  genero: "Relações",
  nivel: "A2",
  desc: "Dez anos depois do seu intercâmbio, você volta a Hamburgo para os 35 anos do seu amigo Paul. A namorada dele mal disfarça a antipatia, e Paul parece esconder alguma coisa.",
  inicio: "c1",
  cenas: {
    c1: {
      cap: "Hamburgo",
      p: [
        ["Nach zehn Jahren bist du wieder in Hamburg. Heute Abend feiert Paul seinen fünfunddreißigsten Geburtstag. Er wartet am Bahnhof mit einem breiten Lachen. Er umarmt dich lange. „Du bist alt geworden!“, sagt er. Aber er sieht müde aus, und er schaut oft auf sein Handy.",
         "Depois de dez anos, você está de volta a Hamburgo. Hoje à noite Paul comemora seus trinta e cinco anos. Ele espera na estação com um sorriso enorme. Ele abraça você demoradamente. “Você ficou velho!”, diz ele. Mas ele parece cansado e olha muitas vezes para o celular.",
         [["Nach zehn Jahren","Depois de dez anos,","nach|zehn|Jahr"],
          ["bist du wieder in Hamburg.","você está de volta a Hamburgo.","sein|du|wieder|in"],
          ["Heute Abend feiert Paul","Hoje à noite Paul comemora","heute|Abend|feiern"],
          ["seinen fünfunddreißigsten Geburtstag.","seus trinta e cinco anos.","sein|Geburtstag"],
          ["Er wartet am Bahnhof","Ele espera na estação","er|warten|an|der|Bahnhof"],
          ["mit einem breiten Lachen.","com um sorriso enorme.","mit|ein|breit"],
          ["Er umarmt dich lange.","Ele abraça você demoradamente.","er|umarmen|du|lang"],
          ["„Du bist alt geworden!“,","“Você ficou velho!”,","du|sein|alt|werden"],
          ["sagt er.","diz ele.","sagen|er"],
          ["Aber er sieht müde aus,","Mas ele parece cansado","aber|er|aussehen|müde"],
          ["und er schaut oft","e olha muitas vezes","und|er|schauen|oft"],
          ["auf sein Handy.","para o celular.","auf|sein|Handy"]]],
        ["Seine Wohnung liegt in Altona, im vierten Stock. Miriam, seine Freundin, öffnet die Tür. Sie gibt dir die Hand, nicht mehr. „Paul erzählt viel von dir“, sagt sie kalt. Auf dem Tisch liegen Briefe, und Paul legt schnell eine Zeitung darauf.",
         "O apartamento dele fica em Altona, no quarto andar. Miriam, a namorada dele, abre a porta. Ela aperta sua mão, nada mais. “Paul fala muito de você”, diz ela, fria. Na mesa há cartas, e Paul coloca depressa um jornal por cima.",
         [["Seine Wohnung liegt","O apartamento dele fica","sein|Wohnung|liegen"],
          ["in Altona,","em Altona,","in"],
          ["im vierten Stock.","no quarto andar.","in|der"],
          ["Miriam, seine Freundin,","Miriam, a namorada dele,","sein|Freundin"],
          ["öffnet die Tür.","abre a porta.","öffnen|der|Tür"],
          ["Sie gibt dir die Hand,","Ela aperta sua mão,","sie|geben|du|der|Hand"],
          ["nicht mehr.","nada mais.","nicht|mehr"],
          ["„Paul erzählt viel von dir“,","“Paul fala muito de você”,","erzählen|viel|von|du"],
          ["sagt sie kalt.","diz ela, fria.","sagen|sie|kalt"],
          ["Auf dem Tisch liegen Briefe,","Na mesa há cartas,","auf|der|Tisch|liegen|Brief"],
          ["und Paul legt schnell","e Paul coloca depressa","und|legen|schnell"],
          ["eine Zeitung darauf.","um jornal por cima.","ein|Zeitung"]]]
      ],
      escolhas: [
        { pt: "Ajudar Miriam na cozinha.", de: "Miriam in der Küche helfen.", ir: "c2a" },
        { pt: "Ir com Paul comprar bebidas para a festa.", de: "Mit Paul Getränke kaufen gehen.", ir: "c2b" }
      ]
    },

    c2a: {
      cap: "A cozinha",
      p: [
        ["In der Küche schneidet Miriam Zwiebeln. Lange sagt sie nichts. Dann legt sie das Messer weg. „Vor zehn Jahren bist du gegangen, ohne ein Wort. Paul hat am Flughafen auf dich gewartet. Zwei Stunden.“",
         "Na cozinha, Miriam corta cebolas. Por muito tempo, ela não diz nada. Depois deixa a faca de lado. “Dez anos atrás, você foi embora, sem uma palavra. No aeroporto, Paul esperou por você. Duas horas.”",
         [["In der Küche","Na cozinha,","in|der|Küche"],
          ["schneidet Miriam Zwiebeln.","Miriam corta cebolas.","schneiden|Zwiebel"],
          ["Lange sagt sie nichts.","Por muito tempo, ela não diz nada.","lang|sagen|sie|nichts"],
          ["Dann legt sie","Depois ela deixa","dann|legen|sie"],
          ["das Messer weg.","a faca de lado.","der|Messer|weg"],
          ["„Vor zehn Jahren","“Dez anos atrás,","vor|zehn|Jahr"],
          ["bist du gegangen,","você foi embora,","sein|du|gehen"],
          ["ohne ein Wort.","sem uma palavra.","ohne|ein|Wort"],
          ["Paul hat am Flughafen","No aeroporto, Paul","haben|an|der|Flughafen"],
          ["auf dich gewartet.","esperou por você.","auf|du|warten"],
          ["Zwei Stunden.“","Duas horas.”","zwei|Stunde"]]],
        ["Sie schaut dich an. „Mit Paul stimmt etwas nicht. Er sagt, er geht jeden Morgen ins Büro. Aber gestern hat ein Kollege angerufen. Er hat gesagt: ‚Wir vermissen Paul in der Firma.‘ Was bedeutet das? Weißt du etwas?“",
         "Ela olha para você. “Tem alguma coisa errada com o Paul. Ele diz que vai toda manhã ao escritório. Mas ontem um colega ligou. Ele disse: ‘Sentimos falta do Paul na empresa.’ O que isso quer dizer? Você sabe de alguma coisa?”",
         [["Sie schaut dich an.","Ela olha para você.","sie|schauen|du"],
          ["„Mit Paul stimmt etwas nicht.","“Tem alguma coisa errada com o Paul.","mit|stimmen|etwas|nicht"],
          ["Er sagt,","Ele diz","er|sagen"],
          ["er geht jeden Morgen","que vai toda manhã","er|gehen|jeder|Morgen"],
          ["ins Büro.","ao escritório.","in|der|Büro"],
          ["Aber gestern","Mas ontem","aber|gestern"],
          ["hat ein Kollege angerufen.","um colega ligou.","haben|ein|Kollege|anrufen"],
          ["Er hat gesagt:","Ele disse:","er|haben|sagen"],
          ["‚Wir vermissen Paul","‘Sentimos falta do Paul","wir|vermissen"],
          ["in der Firma.‘","na empresa.’","in|der|Firma"],
          ["Was bedeutet das?","O que isso quer dizer?","was|bedeuten|das"],
          ["Weißt du etwas?“","Você sabe de alguma coisa?”","wissen|du|etwas"]]]
      ],
      escolhas: [
        { pt: "Ir buscar Anna, a irmã de Paul, que está chegando com o bolo, e perguntar a ela.", de: "Anna unten abholen und sie fragen.", ir: "c3a" },
        { pt: "Ir direto falar com Paul.", de: "Direkt mit Paul reden.", ir: "c3b" }
      ]
    },

    c2b: {
      cap: "O supermercado",
      p: [
        ["Im Supermarkt kauft Paul Bier, Wein und viel zu viel Käse. „Heute bezahle ich alles!“, sagt er laut. An der Kasse gibt er seine Karte. Die Frau schüttelt den Kopf. Er versucht es noch einmal. Wieder nichts.",
         "No supermercado, Paul compra cerveja, vinho e queijo demais. “Hoje eu pago tudo!”, diz ele, alto. No caixa, ele entrega o cartão. A mulher balança a cabeça. Ele tenta mais uma vez. De novo, nada.",
         [["Im Supermarkt","No supermercado,","in|der|Supermarkt"],
          ["kauft Paul Bier, Wein","Paul compra cerveja, vinho","kaufen|Bier|Wein"],
          ["und viel zu viel Käse.","e queijo demais.","und|viel|zu|Käse"],
          ["„Heute bezahle ich alles!“,","“Hoje eu pago tudo!”,","heute|bezahlen|ich|alles"],
          ["sagt er laut.","diz ele, alto.","sagen|er|laut"],
          ["An der Kasse","No caixa,","an|der|Kasse"],
          ["gibt er seine Karte.","ele entrega o cartão.","geben|er|sein|Karte"],
          ["Die Frau schüttelt den Kopf.","A mulher balança a cabeça.","der|Frau|der|Kopf"],
          ["Er versucht es noch einmal.","Ele tenta mais uma vez.","er|versuchen|es|noch"],
          ["Wieder nichts.","De novo, nada.","wieder|nichts"]]],
        ["Du bezahlst. Draußen sagt Paul lange nichts. Dann lacht er, aber es klingt falsch. „Das ist nur ein Problem mit der Bank. Ich erkläre es dir später.“ Er hält deinen Arm fest. „Bitte sag Miriam nichts. Nicht heute.“",
         "Você paga. Lá fora, Paul fica muito tempo calado. Depois ele ri, mas soa falso. “É só um problema com o banco. Eu te explico depois.” Ele segura seu braço. “Por favor, não diga nada à Miriam. Hoje não.”",
         [["Du bezahlst.","Você paga.","du|bezahlen"],
          ["Draußen sagt Paul lange nichts.","Lá fora, Paul fica muito tempo calado.","draußen|sagen|lang|nichts"],
          ["Dann lacht er,","Depois ele ri,","dann|lachen|er"],
          ["aber es klingt falsch.","mas soa falso.","aber|es|klingen|falsch"],
          ["„Das ist nur ein Problem","“É só um problema","das|sein|nur|ein|Problem"],
          ["mit der Bank.","com o banco.","mit|der|Bank"],
          ["Ich erkläre es dir später.“","Eu te explico depois.”","ich|erklären|es|du|später"],
          ["Er hält deinen Arm fest.","Ele segura seu braço.","er|halten|dein|Arm"],
          ["„Bitte sag Miriam nichts.","“Por favor, não diga nada à Miriam.","bitte|sagen|nichts"],
          ["Nicht heute.“","Hoje não.”","nicht|heute"]]]
      ],
      escolhas: [
        { pt: "Prometer que não vai dizer nada.", de: "Versprechen, nichts zu sagen.", ir: "c3a", marca: "segredo_paul" },
        { pt: "Insistir numa explicação.", de: "Auf einer Erklärung bestehen.", ir: "c3b" }
      ]
    },

    c3a: {
      cap: "A irmã",
      p: [
        ["Am Nachmittag klingelt es. Unten steht Anna, Pauls Schwester, mit einem großen Kuchen. „Hilf mir mal“, sagt sie. Auf der Treppe bleibt sie plötzlich stehen. „Du weißt es noch nicht, oder? Paul hat seinen Job verloren. Schon im März.“",
         "À tarde, a campainha toca. Lá embaixo está Anna, a irmã de Paul, com um bolo grande. “Me ajuda aqui”, diz ela. Na escada, ela para de repente. “Você ainda não sabe, né? Paul perdeu o emprego. Já em março.”",
         [["Am Nachmittag","À tarde,","an|der|Nachmittag"],
          ["klingelt es.","a campainha toca.","klingeln|es"],
          ["Unten steht Anna,","Lá embaixo está Anna,","unten|stehen"],
          ["Pauls Schwester,","a irmã de Paul,","Schwester"],
          ["mit einem großen Kuchen.","com um bolo grande.","mit|ein|groß|Kuchen"],
          ["„Hilf mir mal“,","“Me ajuda aqui”,","helfen|ich|mal"],
          ["sagt sie.","diz ela.","sagen|sie"],
          ["Auf der Treppe","Na escada,","auf|der|Treppe"],
          ["bleibt sie plötzlich stehen.","ela para de repente.","bleiben|sie|stehen"],
          ["„Du weißt es noch nicht,","“Você ainda não sabe,","du|wissen|es|noch|nicht"],
          ["oder?","né?","oder"],
          ["Paul hat seinen Job verloren.","Paul perdeu o emprego.","haben|sein|Job|verlieren"],
          ["Schon im März.“","Já em março.”","schon|in|der"]]],
        ["Sie atmet tief. „Ich habe ihm achttausend Euro geliehen. Für die Miete und für heute Abend. Und noch etwas: Vor zehn Jahren habe ich Papa gesagt, dass Paul nicht mehr studiert. Ich, nicht du. Paul glaubt bis heute, du warst es.“",
         "Ela respira fundo. “Eu emprestei a ele oito mil euros. Para o aluguel e para hoje à noite. E tem mais uma coisa: dez anos atrás, eu contei ao papai que Paul não estudava mais. Eu, não você. Paul acredita até hoje que foi você.”",
         [["Sie atmet tief.","Ela respira fundo.","sie|atmen|tief"],
          ["„Ich habe ihm","“Eu emprestei a ele","ich|haben|er"],
          ["achttausend Euro geliehen.","oito mil euros.","Euro|leihen"],
          ["Für die Miete","Para o aluguel","für|der|Miete"],
          ["und für heute Abend.","e para hoje à noite.","und|für|heute|Abend"],
          ["Und noch etwas:","E tem mais uma coisa:","und|noch|etwas"],
          ["Vor zehn Jahren","dez anos atrás,","vor|zehn|Jahr"],
          ["habe ich Papa gesagt,","eu contei ao papai","haben|ich|sagen"],
          ["dass Paul nicht mehr studiert.","que Paul não estudava mais.","dass|nicht|mehr|studieren"],
          ["Ich, nicht du.","Eu, não você.","ich|nicht|du"],
          ["Paul glaubt bis heute,","Paul acredita até hoje","glauben|bis|heute"],
          ["du warst es.“","que foi você.”","du|sein|es"]]],
        ["Ihre Augen sind nass. „Bitte sag ihm heute nichts. Nicht über das Geld, nicht über Papa. Er braucht mich jetzt, und er braucht dich. Morgen rede ich mit ihm. Versprochen.“",
         "Os olhos dela estão molhados. “Por favor, não diga nada a ele hoje. Nem sobre o dinheiro, nem sobre o papai. Ele precisa de mim agora, e precisa de você. Amanhã eu falo com ele. Prometo.”",
         [["Ihre Augen sind nass.","Os olhos dela estão molhados.","ihr|Auge|sein|nass"],
          ["„Bitte sag ihm heute nichts.","“Por favor, não diga nada a ele hoje.","bitte|sagen|er|heute|nichts"],
          ["Nicht über das Geld,","Nem sobre o dinheiro,","nicht|über|der|Geld"],
          ["nicht über Papa.","nem sobre o papai.","nicht|über"],
          ["Er braucht mich jetzt,","Ele precisa de mim agora,","er|brauchen|ich|jetzt"],
          ["und er braucht dich.","e precisa de você.","und|er|brauchen|du"],
          ["Morgen rede ich mit ihm.","Amanhã eu falo com ele.","morgen|reden|ich|mit|er"],
          ["Versprochen.“","Prometo.”",""]]]
      ],
      escolhas: [
        { pt: "Aceitar: guardar os dois segredos esta noite.", de: "Ja sagen und heute schweigen.", ir: "c4a", marca: "segredo_anna" },
        { pt: "Recusar: você carregou a culpa dela por dez anos.", de: "Nein sagen. Zehn Jahre sind genug.", ir: "c4b" }
      ]
    },

    c3b: {
      cap: "A varanda",
      p: [
        ["Eine Stunde später sitzt ihr allein auf dem Balkon. Paul raucht, obwohl er nicht mehr raucht. „Okay“, sagt er endlich. „Ich habe meinen Job verloren. Im März. Anna hat mir Geld geliehen. Miriam weiß nichts.“",
         "Uma hora depois, vocês estão sentados sozinhos na varanda. Paul fuma, embora tenha parado de fumar. “Tá bom”, diz ele, finalmente. “Eu perdi o emprego. Em março. A Anna me emprestou dinheiro. A Miriam não sabe de nada.”",
         [["Eine Stunde später","Uma hora depois,","ein|Stunde|später"],
          ["sitzt ihr allein","vocês estão sentados sozinhos","sitzen|ihr|allein"],
          ["auf dem Balkon.","na varanda.","auf|der"],
          ["Paul raucht,","Paul fuma,","rauchen"],
          ["obwohl er nicht mehr raucht.","embora tenha parado de fumar.","obwohl|er|nicht|mehr|rauchen"],
          ["„Okay“,","“Tá bom”,","okay"],
          ["sagt er endlich.","diz ele, finalmente.","sagen|er|endlich"],
          ["„Ich habe meinen Job verloren.","“Eu perdi o emprego.","ich|haben|mein|Job|verlieren"],
          ["Im März.","Em março.","in|der"],
          ["Anna hat mir Geld geliehen.","A Anna me emprestou dinheiro.","haben|ich|Geld|leihen"],
          ["Miriam weiß nichts.“","A Miriam não sabe de nada.”","wissen|nichts"]]],
        ["Er sieht dich an. „Weißt du noch? Vor zehn Jahren hast du Papa gesagt, dass ich nicht mehr studiere. Ich habe dir verziehen. Jetzt bitte ich dich: Sag Miriam nichts. Nur bis morgen.“ Aber das stimmt nicht: Du warst es nicht. Das weiß er nur nicht.",
         "Ele olha para você. “Lembra? Dez anos atrás, você contou ao meu pai que eu não estudava mais. Eu te perdoei. Agora eu te peço: não diga nada à Miriam. Só até amanhã.” Mas isso não é verdade: não foi você. Ele só não sabe disso.",
         [["Er sieht dich an.","Ele olha para você.","er|sehen|du"],
          ["„Weißt du noch?","“Lembra?","wissen|du|noch"],
          ["Vor zehn Jahren","Dez anos atrás,","vor|zehn|Jahr"],
          ["hast du Papa gesagt,","você contou ao meu pai","haben|du|sagen"],
          ["dass ich nicht mehr studiere.","que eu não estudava mais.","dass|ich|nicht|mehr|studieren"],
          ["Ich habe dir verziehen.","Eu te perdoei.","ich|haben|du|verzeihen"],
          ["Jetzt bitte ich dich:","Agora eu te peço:","jetzt|bitten|ich|du"],
          ["Sag Miriam nichts.","não diga nada à Miriam.","sagen|nichts"],
          ["Nur bis morgen.“","Só até amanhã.”","nur|bis|morgen"],
          ["Aber das stimmt nicht:","Mas isso não é verdade:","aber|das|stimmen|nicht"],
          ["Du warst es nicht.","não foi você.","du|sein|es|nicht"],
          ["Das weiß er nur nicht.","Ele só não sabe disso.","das|wissen|er|nur|nicht"]]]
      ],
      escolhas: [
        { pt: "Prometer ficar calado até amanhã.", de: "Versprechen, bis morgen zu schweigen.", ir: "c4a", marca: "segredo_paul" },
        { pt: "Dizer que não vai mentir por ele.", de: "Sagen, dass du nicht für ihn lügst.", ir: "c4b" }
      ]
    },

    c4a: {
      cap: "O brinde",
      p: [
        ["Am Abend ist die Wohnung voll. Dreißig Gäste, laute Musik. Paul trägt ein neues Hemd und lacht viel. Miriam beobachtet dich aus der Küche. Anna bringt den Kuchen und sieht dich nicht an. Dann klopft Paul an sein Glas.",
         "À noite, o apartamento está cheio. Trinta convidados, música alta. Paul está com uma camisa nova e ri muito. Miriam observa você da cozinha. Anna traz o bolo e não olha para você. Então Paul bate no copo.",
         [["Am Abend","À noite,","an|der|Abend"],
          ["ist die Wohnung voll.","o apartamento está cheio.","sein|der|Wohnung|voll"],
          ["Dreißig Gäste,","Trinta convidados,","Gast"],
          ["laute Musik.","música alta.","laut|Musik"],
          ["Paul trägt ein neues Hemd","Paul está com uma camisa nova","tragen|ein|neu|Hemd"],
          ["und lacht viel.","e ri muito.","und|lachen|viel"],
          ["Miriam beobachtet dich","Miriam observa você","beobachten|du"],
          ["aus der Küche.","da cozinha.","aus|der|Küche"],
          ["Anna bringt den Kuchen","Anna traz o bolo","bringen|der|Kuchen"],
          ["und sieht dich nicht an.","e não olha para você.","und|sehen|du|nicht"],
          ["Dann klopft Paul","Então Paul bate","dann|klopfen"],
          ["an sein Glas.","no copo.","an|sein|Glas"]]],
        ["„Danke, dass ihr alle da seid! Danke an Anna, für alles. Und danke an meinen ältesten Freund: Er ist aus Brasilien gekommen!“ Alle klatschen. „Vor zehn Jahren hat er Papa alles erzählt. Aber ich habe ihm verziehen!“ Einige Gäste lachen. Anna wird ganz weiß.",
         "“Obrigado por vocês todos estarem aqui! Obrigado à Anna, por tudo. E obrigado ao meu amigo mais antigo: ele veio do Brasil!” Todos aplaudem. “Dez anos atrás, ele contou tudo ao meu pai. Mas eu o perdoei!” Alguns convidados riem. Anna fica pálida.",
         [["„Danke,","“Obrigado","danke"],
          ["dass ihr alle da seid!","por vocês todos estarem aqui!","dass|ihr|alle|da|sein"],
          ["Danke an Anna,","Obrigado à Anna,","danke|an"],
          ["für alles.","por tudo.","für|alles"],
          ["Und danke","E obrigado","und|danke"],
          ["an meinen ältesten Freund:","ao meu amigo mais antigo:","an|mein|alt|Freund"],
          ["Er ist aus Brasilien gekommen!“","ele veio do Brasil!”","er|sein|aus|kommen"],
          ["Alle klatschen.","Todos aplaudem.","alle"],
          ["„Vor zehn Jahren","“Dez anos atrás,","vor|zehn|Jahr"],
          ["hat er Papa alles erzählt.","ele contou tudo ao meu pai.","haben|er|alles|erzählen"],
          ["Aber ich habe ihm verziehen!“","Mas eu o perdoei!”","aber|ich|haben|er|verzeihen"],
          ["Einige Gäste lachen.","Alguns convidados riem.","einige|Gast|lachen"],
          ["Anna wird ganz weiß.","Anna fica pálida.","werden|ganz|weiß"]]]
      ],
      escolhas: [
        { pt: "Sorrir e ficar calado, pela promessa feita a Anna.", de: "Lächeln und schweigen.", ir: "f_silencio", req: "segredo_anna" },
        { pt: "Dizer na frente de todos que não foi você.", de: "Vor allen sagen: „Das war ich nicht.“", ir: "c5b" },
        { pt: "Esperar o fim do discurso e chamar Paul para conversar a sós.", de: "Später allein mit Paul reden.", ir: "c5a" }
      ]
    },

    c4b: {
      cap: "O quarto",
      p: [
        ["Um acht Uhr kommen die ersten Gäste. Miriam nimmt deinen Arm und zieht dich in das kleine Zimmer. Sie schließt die Tür. „Du weißt etwas. Ich sehe es in deinem Gesicht.“ Draußen lacht Paul, laut und glücklich.",
         "Às oito horas chegam os primeiros convidados. Miriam pega seu braço e puxa você para o quarto pequeno. Ela fecha a porta. “Você sabe de alguma coisa. Eu vejo isso no seu rosto.” Lá fora, Paul ri, alto e feliz.",
         [["Um acht Uhr","Às oito horas","um|acht|Uhr"],
          ["kommen die ersten Gäste.","chegam os primeiros convidados.","kommen|der|erste|Gast"],
          ["Miriam nimmt deinen Arm","Miriam pega seu braço","nehmen|dein|Arm"],
          ["und zieht dich","e puxa você","und|ziehen|du"],
          ["in das kleine Zimmer.","para o quarto pequeno.","in|der|klein|Zimmer"],
          ["Sie schließt die Tür.","Ela fecha a porta.","sie|schließen|der|Tür"],
          ["„Du weißt etwas.","“Você sabe de alguma coisa.","du|wissen|etwas"],
          ["Ich sehe es","Eu vejo isso","ich|sehen|es"],
          ["in deinem Gesicht.“","no seu rosto.”","in|dein|Gesicht"],
          ["Draußen lacht Paul,","Lá fora, Paul ri,","draußen|lachen"],
          ["laut und glücklich.","alto e feliz.","laut|und|glücklich"]]],
        ["„Ich liebe ihn“, sagt sie leise. „Aber ich will keine Lügen mehr. Seit drei Monaten ist er ein anderer Mensch. Er schläft nicht, er isst nicht. Ich habe Angst. Bitte sag mir die Wahrheit.“",
         "“Eu o amo”, diz ela baixinho. “Mas eu não quero mais mentiras. Há três meses ele é outra pessoa. Ele não dorme, não come. Estou com medo. Por favor, me diga a verdade.”",
         [["„Ich liebe ihn“,","“Eu o amo”,","ich|lieben|er"],
          ["sagt sie leise.","diz ela baixinho.","sagen|sie|leise"],
          ["„Aber ich will","“Mas eu não quero","aber|ich|wollen"],
          ["keine Lügen mehr.","mais mentiras.","kein|Lüge|mehr"],
          ["Seit drei Monaten","Há três meses","seit|drei|Monat"],
          ["ist er ein anderer Mensch.","ele é outra pessoa.","sein|er|ein|ander|Mensch"],
          ["Er schläft nicht,","Ele não dorme,","er|schlafen|nicht"],
          ["er isst nicht.","não come.","er|essen|nicht"],
          ["Ich habe Angst.","Estou com medo.","ich|haben|Angst"],
          ["Bitte sag mir","Por favor, me diga","bitte|sagen|ich"],
          ["die Wahrheit.“","a verdade.”","der|Wahrheit"]]]
      ],
      escolhas: [
        { pt: "Contar tudo a Miriam: o emprego e o dinheiro de Anna.", de: "Miriam die Wahrheit sagen.", ir: "c5b", marca: "contou_miriam" },
        { pt: "Dizer que quem precisa contar é o Paul, e ir buscá-lo.", de: "Sagen: „Das muss Paul dir sagen.“ Dann Paul holen.", ir: "c5a" },
        { pt: "Mentir, como prometeu a Paul: dizer que não sabe de nada.", de: "Lügen und sagen, dass du nichts weißt.", ir: "f_silencio", req: "segredo_paul" }
      ]
    },

    c5a: {
      cap: "Meia-noite",
      p: [
        ["Kurz vor Mitternacht stehst du mit Paul auf dem Balkon. Unten fährt ein Bus vorbei. Paul hat viel getrunken. „Weißt du, was komisch ist?“, fragt er. „Ich war nie böse. Nur traurig. Warum hast du das getan?“",
         "Pouco antes da meia-noite, você está com Paul na varanda. Lá embaixo passa um ônibus. Paul bebeu muito. “Sabe o que é engraçado?”, pergunta ele. “Eu nunca fiquei com raiva. Só triste. Por que você fez aquilo?”",
         [["Kurz vor Mitternacht","Pouco antes da meia-noite,","kurz|vor"],
          ["stehst du mit Paul","você está com Paul","stehen|du|mit"],
          ["auf dem Balkon.","na varanda.","auf|der"],
          ["Unten fährt ein Bus vorbei.","Lá embaixo passa um ônibus.","unten|fahren|ein|Bus"],
          ["Paul hat viel getrunken.","Paul bebeu muito.","haben|viel|trinken"],
          ["„Weißt du,","“Sabe","wissen|du"],
          ["was komisch ist?“,","o que é engraçado?”,","was|sein"],
          ["fragt er.","pergunta ele.","fragen|er"],
          ["„Ich war nie böse.","“Eu nunca fiquei com raiva.","ich|sein|nie|böse"],
          ["Nur traurig.","Só triste.","nur|traurig"],
          ["Warum hast du das getan?“","Por que você fez aquilo?”","warum|haben|du|das|tun"]]],
        ["Hinter dem Fenster siehst du Anna. Sie schaut zu euch, mit großen Augen. Paul wartet auf eine Antwort. Er hat keinen Job und keine Ruhe. Du kannst ihm jetzt viel sagen. Oder sehr wenig.",
         "Atrás da janela, você vê Anna. Ela olha para vocês, de olhos arregalados. Paul espera uma resposta. Ele não tem emprego nem paz. Agora você pode dizer muito a ele. Ou muito pouco.",
         [["Hinter dem Fenster","Atrás da janela,","hinter|der|Fenster"],
          ["siehst du Anna.","você vê Anna.","sehen|du"],
          ["Sie schaut zu euch,","Ela olha para vocês,","sie|schauen|zu|ihr"],
          ["mit großen Augen.","de olhos arregalados.","mit|groß|Auge"],
          ["Paul wartet","Paul espera","warten"],
          ["auf eine Antwort.","uma resposta.","auf|ein|Antwort"],
          ["Er hat keinen Job","Ele não tem emprego","er|haben|kein|Job"],
          ["und keine Ruhe.","nem paz.","und|kein|Ruhe"],
          ["Du kannst ihm jetzt","Agora você pode","du|können|er|jetzt"],
          ["viel sagen.","dizer muito a ele.","viel|sagen"],
          ["Oder sehr wenig.","Ou muito pouco.","oder|sehr"]]]
      ],
      escolhas: [
        { pt: "Dizer que não foi você e que hoje tudo precisa vir à tona: o emprego, o dinheiro, o passado.", de: "Sagen: „Ich war es nicht. Heute Nacht sagen wir alles.“", ir: "f_renovada" },
        { pt: "Mudar de assunto e buscar mais uma cerveja.", de: "Das Thema wechseln und noch ein Bier holen.", ir: "f_silencio" },
        { pt: "Cumprir a promessa a Anna: dizer só “não fui eu”, sem nomes.", de: "Nur sagen: „Ich war es nicht.“ Keine Namen.", ir: "f_distancia", req: "segredo_anna" }
      ]
    },

    c5b: {
      cap: "A cozinha à noite",
      p: [
        ["Eine halbe Stunde später ist die Musik aus. Die Gäste stehen still im Flur. In der Küche steht Paul, sein Gesicht ist rot. „Warum hast du das gemacht?“, fragt er. „Heute? An meinem Geburtstag?“",
         "Meia hora depois, a música está desligada. Os convidados estão parados no corredor, em silêncio. Na cozinha está Paul, o rosto dele está vermelho. “Por que você fez isso?”, pergunta ele. “Hoje? No meu aniversário?”",
         [["Eine halbe Stunde später","Meia hora depois,","ein|Stunde|später"],
          ["ist die Musik aus.","a música está desligada.","sein|der|Musik"],
          ["Die Gäste stehen still","Os convidados estão parados, em silêncio,","der|Gast|stehen"],
          ["im Flur.","no corredor.","in|der"],
          ["In der Küche","Na cozinha","in|der|Küche"],
          ["steht Paul,","está Paul,","stehen"],
          ["sein Gesicht ist rot.","o rosto dele está vermelho.","sein|Gesicht|rot"],
          ["„Warum hast du das gemacht?“,","“Por que você fez isso?”,","warum|haben|du|das|machen"],
          ["fragt er.","pergunta ele.","fragen|er"],
          ["„Heute?","“Hoje?","heute"],
          ["An meinem Geburtstag?“","No meu aniversário?”","an|mein|Geburtstag"]]],
        ["Miriam steht am Fenster und sagt nichts. Anna weint im Bad. Paul schaut nur dich an. „Ich habe dich eingeladen“, sagt Paul. „Ich habe mich so gefreut. Und du machst alles kaputt.“",
         "Miriam está na janela e não diz nada. Anna chora no banheiro. Paul só olha para você. “Eu convidei você”, diz Paul. “Eu fiquei tão feliz. E você estraga tudo.”",
         [["Miriam steht am Fenster","Miriam está na janela","stehen|an|der|Fenster"],
          ["und sagt nichts.","e não diz nada.","und|sagen|nichts"],
          ["Anna weint im Bad.","Anna chora no banheiro.","weinen|in|der|Bad"],
          ["Paul schaut nur dich an.","Paul só olha para você.","schauen|nur|du"],
          ["„Ich habe dich eingeladen“,","“Eu convidei você”,","ich|haben|du|einladen"],
          ["sagt Paul.","diz Paul.","sagen"],
          ["„Ich habe mich so gefreut.","“Eu fiquei tão feliz.","ich|haben|so|freuen"],
          ["Und du machst alles kaputt.“","E você estraga tudo.”","und|du|machen|alles"]]]
      ],
      escolhas: [
        { pt: "Se defender: foram dez anos carregando uma culpa que não era sua.", de: "Dich verteidigen: „Zehn Jahre war ich der Schuldige!“", ir: "f_ruptura" },
        { pt: "Pedir desculpas pelo momento, mas não pela verdade.", de: "Dich für den Moment entschuldigen, nicht für die Wahrheit.", ir: "f_distancia" },
        { pt: "Olhar para Miriam e deixar que ela fale.", de: "Miriam ansehen und sie sprechen lassen.", ir: "f_renovada", req: "contou_miriam" }
      ]
    },

    f_renovada: {
      cap: "Quatro na cozinha",
      p: [
        ["Es wird eine lange Nacht. Um drei Uhr sitzt ihr in der Küche: Paul, Miriam, Anna und du. Anna erzählt selbst, was damals passiert ist. Paul sagt lange nichts. Dann lacht er, und gleichzeitig weint er. „Zehn Jahre“, sagt er leise.",
         "Vai ser uma longa noite. Às três horas, vocês estão sentados na cozinha: Paul, Miriam, Anna e você. A própria Anna conta o que aconteceu naquela época. Paul fica muito tempo em silêncio. Depois ele ri e, ao mesmo tempo, chora. “Dez anos”, diz ele baixinho.",
         [["Es wird eine lange Nacht.","Vai ser uma longa noite.","es|werden|ein|lang|Nacht"],
          ["Um drei Uhr","Às três horas,","um|drei|Uhr"],
          ["sitzt ihr in der Küche:","vocês estão sentados na cozinha:","sitzen|ihr|in|der|Küche"],
          ["Paul, Miriam, Anna und du.","Paul, Miriam, Anna e você.","und|du"],
          ["Anna erzählt selbst,","A própria Anna conta","erzählen"],
          ["was damals passiert ist.","o que aconteceu naquela época.","was|passieren|sein"],
          ["Paul sagt lange nichts.","Paul fica muito tempo em silêncio.","sagen|lang|nichts"],
          ["Dann lacht er,","Depois ele ri","dann|lachen|er"],
          ["und gleichzeitig weint er.","e, ao mesmo tempo, chora.","und|weinen|er"],
          ["„Zehn Jahre“,","“Dez anos”,","zehn|Jahr"],
          ["sagt er leise.","diz ele baixinho.","sagen|er|leise"]]],
        ["Am Morgen sind die Probleme nicht weg. Paul hat keinen Job, und Anna bekommt noch viel Geld von ihm. Miriam ist noch kalt, aber sie kocht dir Kaffee. An der Tür umarmt Paul dich. „Bleib noch einen Tag. Bitte.“",
         "De manhã, os problemas não sumiram. Paul não tem emprego, e Anna ainda vai receber muito dinheiro dele. Miriam ainda está fria, mas faz um café para você. Na porta, Paul abraça você. “Fica mais um dia. Por favor.”",
         [["Am Morgen","De manhã,","an|der|Morgen"],
          ["sind die Probleme nicht weg.","os problemas não sumiram.","sein|der|Problem|nicht|weg"],
          ["Paul hat keinen Job,","Paul não tem emprego,","haben|kein|Job"],
          ["und Anna bekommt","e Anna ainda vai receber","und|bekommen"],
          ["noch viel Geld von ihm.","muito dinheiro dele.","noch|viel|Geld|von|er"],
          ["Miriam ist noch kalt,","Miriam ainda está fria,","sein|noch|kalt"],
          ["aber sie kocht dir Kaffee.","mas faz um café para você.","aber|sie|kochen|du|Kaffee"],
          ["An der Tür","Na porta,","an|der|Tür"],
          ["umarmt Paul dich.","Paul abraça você.","umarmen|du"],
          ["„Bleib noch einen Tag.","“Fica mais um dia.","bleiben|noch|ein|Tag"],
          ["Bitte.“","Por favor.”","bitte"]]]
      ],
      fim: { tipo: "bom", titulo: "Amizade renovada" }
    },

    f_distancia: {
      cap: "A estação",
      p: [
        ["Am nächsten Morgen fährst du nach Hause, einen Tag zu früh. Paul bringt dich zum Bahnhof. Ihr redet über Fußball, über das Wetter, über alte Freunde. Über gestern Abend sagt ihr nichts. Am Zug gibt er dir die Hand. Dann umarmt er dich doch.",
         "Na manhã seguinte, você volta para casa, um dia antes do previsto. Paul leva você até a estação. Vocês falam de futebol, do tempo, de velhos amigos. Sobre ontem à noite, vocês não dizem nada. No trem, ele aperta sua mão. Depois, mesmo assim, abraça você.",
         [["Am nächsten Morgen","Na manhã seguinte,","an|der|nächste|Morgen"],
          ["fährst du nach Hause,","você volta para casa,","fahren|du|nach|Haus"],
          ["einen Tag zu früh.","um dia antes do previsto.","ein|Tag|zu|früh"],
          ["Paul bringt dich","Paul leva você","bringen|du"],
          ["zum Bahnhof.","até a estação.","zu|der|Bahnhof"],
          ["Ihr redet über Fußball,","Vocês falam de futebol,","ihr|reden|über|Fußball"],
          ["über das Wetter,","do tempo,","über|der|Wetter"],
          ["über alte Freunde.","de velhos amigos.","über|alt|Freund"],
          ["Über gestern Abend","Sobre ontem à noite,","über|gestern|Abend"],
          ["sagt ihr nichts.","vocês não dizem nada.","sagen|ihr|nichts"],
          ["Am Zug","No trem,","an|der|Zug"],
          ["gibt er dir die Hand.","ele aperta sua mão.","geben|er|du|der|Hand"],
          ["Dann umarmt er dich doch.","Depois, mesmo assim, abraça você.","dann|umarmen|er|du|doch"]]],
        ["„Ich brauche Zeit“, sagt er. „Aber ich weiß jetzt, wer du bist.“ Der Zug fährt los. Später schreibt ihr euch zweimal im Jahr, zum Geburtstag und zu Weihnachten. Es ist nicht wie früher. Aber es ist echt.",
         "“Eu preciso de tempo”, diz ele. “Mas agora eu sei quem você é.” O trem parte. Depois disso, vocês trocam mensagens duas vezes por ano, no aniversário e no Natal. Não é como antes. Mas é verdadeiro.",
         [["„Ich brauche Zeit“,","“Eu preciso de tempo”,","ich|brauchen|Zeit"],
          ["sagt er.","diz ele.","sagen|er"],
          ["„Aber ich weiß jetzt,","“Mas agora eu sei","aber|ich|wissen|jetzt"],
          ["wer du bist.“","quem você é.”","wer|du|sein"],
          ["Der Zug fährt los.","O trem parte.","der|Zug|fahren|los"],
          ["Später schreibt ihr euch","Depois disso, vocês trocam mensagens","später|schreiben|ihr"],
          ["zweimal im Jahr,","duas vezes por ano,","in|der|Jahr"],
          ["zum Geburtstag","no aniversário","zu|der|Geburtstag"],
          ["und zu Weihnachten.","e no Natal.","und|zu|Weihnachten"],
          ["Es ist nicht wie früher.","Não é como antes.","es|sein|nicht|wie|früh"],
          ["Aber es ist echt.","Mas é verdadeiro.","aber|es|sein"]]]
      ],
      fim: { tipo: "neutro", titulo: "Distância honesta" }
    },

    f_ruptura: {
      cap: "A escada",
      p: [
        ["„Zehn Jahre war ich der Böse in deiner Geschichte!“, rufst du. „Und ich war es nie!“ Es wird still. Dann sagt Paul ruhig: „Geh. Bitte geh jetzt.“ Niemand hält dich auf. Du nimmst deinen Koffer und gehst die Treppe hinunter.",
         "“Dez anos eu fui o vilão na sua história!”, você grita. “E nunca fui eu!” Faz-se silêncio. Então Paul diz, calmo: “Vai embora. Por favor, vai agora.” Ninguém impede você. Você pega sua mala e desce a escada.",
         [["„Zehn Jahre","“Dez anos","zehn|Jahr"],
          ["war ich der Böse","eu fui o vilão","sein|ich|der|böse"],
          ["in deiner Geschichte!“,","na sua história!”,","in|dein|Geschichte"],
          ["rufst du.","você grita.","rufen|du"],
          ["„Und ich war es nie!“","“E nunca fui eu!”","und|ich|sein|es|nie"],
          ["Es wird still.","Faz-se silêncio.","es|werden"],
          ["Dann sagt Paul ruhig:","Então Paul diz, calmo:","dann|sagen|ruhig"],
          ["„Geh.","“Vai embora.","gehen"],
          ["Bitte geh jetzt.“","Por favor, vai agora.”","bitte|gehen|jetzt"],
          ["Niemand hält dich auf.","Ninguém impede você.","niemand|halten|du"],
          ["Du nimmst deinen Koffer","Você pega sua mala","du|nehmen|dein|Koffer"],
          ["und gehst die Treppe hinunter.","e desce a escada.","und|gehen|der|Treppe"]]],
        ["Die Nacht verbringst du in einem billigen Hotel am Bahnhof. Um sechs Uhr kommt eine Nachricht von Anna: „Es tut mir so leid. Es war mein Fehler.“ Von Paul kommt nichts. Nicht an diesem Tag, nicht an Weihnachten. Du hattest Recht. Aber das hilft dir nicht.",
         "Você passa a noite num hotel barato perto da estação. Às seis horas chega uma mensagem de Anna: “Sinto muito mesmo. Foi culpa minha.” De Paul, nada. Nem naquele dia, nem no Natal. Você tinha razão. Mas isso não te ajuda.",
         [["Die Nacht verbringst du","Você passa a noite","der|Nacht|verbringen|du"],
          ["in einem billigen Hotel","num hotel barato","in|ein|billig|Hotel"],
          ["am Bahnhof.","perto da estação.","an|der|Bahnhof"],
          ["Um sechs Uhr","Às seis horas","um|sechs|Uhr"],
          ["kommt eine Nachricht von Anna:","chega uma mensagem de Anna:","kommen|ein|Nachricht|von"],
          ["„Es tut mir so leid.","“Sinto muito mesmo.","es|tun|ich|so"],
          ["Es war mein Fehler.“","Foi culpa minha.”","es|sein|mein|Fehler"],
          ["Von Paul kommt nichts.","De Paul, nada.","von|kommen|nichts"],
          ["Nicht an diesem Tag,","Nem naquele dia,","nicht|an|dieser|Tag"],
          ["nicht an Weihnachten.","nem no Natal.","nicht|an|Weihnachten"],
          ["Du hattest Recht.","Você tinha razão.","du|haben|Recht"],
          ["Aber das hilft dir nicht.","Mas isso não te ajuda.","aber|das|helfen|du|nicht"]]]
      ],
      fim: { tipo: "ruim", titulo: "Ruptura" }
    },

    f_silencio: {
      cap: "O trem",
      p: [
        ["Ihr feiert bis zwei Uhr. Paul singt, Anna tanzt, Miriam putzt die Küche. Im Flur umarmt Paul dich. „Mein bester Freund“, sagt er. „Wie früher.“ Du lächelst. Aber dein Herz ist schwer.",
         "Vocês comemoram até as duas horas. Paul canta, Anna dança, Miriam limpa a cozinha. No corredor, Paul abraça você. “Meu melhor amigo”, diz ele. “Como antes.” Você sorri. Mas seu coração está pesado.",
         [["Ihr feiert","Vocês comemoram","ihr|feiern"],
          ["bis zwei Uhr.","até as duas horas.","bis|zwei|Uhr"],
          ["Paul singt,","Paul canta,","singen"],
          ["Anna tanzt,","Anna dança,","tanzen"],
          ["Miriam putzt die Küche.","Miriam limpa a cozinha.","putzen|der|Küche"],
          ["Im Flur","No corredor,","in|der"],
          ["umarmt Paul dich.","Paul abraça você.","umarmen|du"],
          ["„Mein bester Freund“,","“Meu melhor amigo”,","mein|best|Freund"],
          ["sagt er.","diz ele.","sagen|er"],
          ["„Wie früher.“","“Como antes.”","wie|früh"],
          ["Du lächelst.","Você sorri.","du"],
          ["Aber dein Herz ist schwer.","Mas seu coração está pesado.","aber|dein|Herz|sein|schwer"]]],
        ["Am nächsten Tag sitzt du im Zug nach Frankfurt. Dein Handy klingelt. Eine Nachricht von Miriam: „Du hast es gewusst, oder?“ Du schaust lange aus dem Fenster. Du schreibst eine Antwort und löschst sie wieder. Dann noch eine. Du schickst keine.",
         "No dia seguinte, você está no trem para Frankfurt. Seu celular toca. Uma mensagem de Miriam: “Você sabia, não sabia?” Você olha muito tempo pela janela. Você escreve uma resposta e apaga de novo. Depois outra. Não envia nenhuma.",
         [["Am nächsten Tag","No dia seguinte,","an|der|nächste|Tag"],
          ["sitzt du im Zug","você está no trem","sitzen|du|in|der|Zug"],
          ["nach Frankfurt.","para Frankfurt.","nach"],
          ["Dein Handy klingelt.","Seu celular toca.","dein|Handy|klingeln"],
          ["Eine Nachricht von Miriam:","Uma mensagem de Miriam:","ein|Nachricht|von"],
          ["„Du hast es gewusst,","“Você sabia,","du|haben|es|wissen"],
          ["oder?“","não sabia?”","oder"],
          ["Du schaust lange","Você olha muito tempo","du|schauen|lang"],
          ["aus dem Fenster.","pela janela.","aus|der|Fenster"],
          ["Du schreibst eine Antwort","Você escreve uma resposta","du|schreiben|ein|Antwort"],
          ["und löschst sie wieder.","e apaga de novo.","und|sie|wieder"],
          ["Dann noch eine.","Depois outra.","dann|noch|ein"],
          ["Du schickst keine.","Não envia nenhuma.","du|schicken|kein"]]]
      ],
      fim: { tipo: "neutro", titulo: "O que não foi dito" }
    }
  }
});
